<?php
require dirname(__DIR__, 2) . '/admin-device.php';
$count = 0;
function check($value, $name) { global $count; if (!$value) throw new RuntimeException('FAIL: ' . $name); $count++; }
putenv('RAILWAY_ENVIRONMENT_ID=railway-test');
$railwayEdge = ['REMOTE_ADDR'=>'127.0.0.1', 'HTTP_X_L8_RAILWAY_REAL_IP'=>'38.196.115.73'];
check(adminClientIp($railwayEdge) === '38.196.115.73', 'Railway client IP');
check(adminClientIp(['REMOTE_ADDR'=>'127.0.0.1', 'HTTP_X_REAL_IP'=>'38.196.115.73']) === '', 'raw Railway X-Real-IP ignored');
check(adminClientIp(array_replace($railwayEdge, ['REMOTE_ADDR'=>'192.0.2.1'])) === '', 'direct Railway internal header ignored');
check(adminClientIp(array_replace($railwayEdge, ['HTTP_X_L8_RAILWAY_REAL_IP'=>'192.0.2.1, 38.196.115.73'])) === '', 'Railway header must contain one address');
putenv('RAILWAY_ENVIRONMENT_ID');

putenv('RENDER=true');
$edge = ['REMOTE_ADDR'=>'127.0.0.1', 'HTTP_X_L8_RENDER_CF_IP'=>'38.196.115.73'];
check(adminClientIp($edge) === '38.196.115.73', 'Render fallback client IP');
check(adminClientIp(['REMOTE_ADDR'=>'127.0.0.1', 'HTTP_X_FORWARDED_FOR'=>'38.196.115.73']) === '', 'ordinary XFF ignored');
check(adminClientIp(array_replace($edge, ['REMOTE_ADDR'=>'192.0.2.1'])) === '', 'direct headers ignored');
check(adminClientIp(array_replace($edge, ['HTTP_X_FORWARDED_FOR'=>'192.0.2.1, 38.196.115.184'])) === '38.196.115.73', 'forged XFF ignored');
check(adminClientIp(array_replace($edge, ['HTTP_X_L8_RENDER_CF_IP'=>'192.0.2.1, 38.196.115.73'])) === '', 'CF header must contain one address');
check(adminClientIp(['REMOTE_ADDR'=>'127.0.0.1','HTTP_X_L8_RENDER_XFF'=>'38.196.115.73']) === '', 'legacy proxy header cannot authorize');
check(adminClientIp(['REMOTE_ADDR'=>'127.0.0.1','HTTP_CF_CONNECTING_IP'=>'38.196.115.73']) === '', 'raw CF header cannot authorize');
putenv('RENDER=false'); check(adminClientIp($edge) === '', 'unconfigured deployment denied'); putenv('RENDER=true');
check(!adminSameOrigin(['HTTP_HOST'=>ADMIN_DEVICE_RP, 'HTTP_ORIGIN'=>'https://evil.example']), 'foreign origin denied');
check(adminSameOrigin(['HTTP_HOST'=>ADMIN_DEVICE_RP, 'HTTP_ORIGIN'=>ADMIN_DEVICE_ORIGIN]), 'same origin accepted');
foreach (['/api/admin/dilithium-verify','/api/auth/dilithium-active-key','/api/auth/list-accounts','/api/auth/suspend-account','/api/auth/reactivate-account','/api/auth/delete-account','/api/auth/delete'] as $path) check(adminProtectedPath($path), $path);
foreach (['/api/auth/login','/api/auth/register','/api/auth/recover','/api/auth/session'] as $path) check(!adminProtectedPath($path), 'user path remains public: ' . $path);
check(!adminTicketValid('forged-ticket', '38.196.115.73'), 'forged CodeKey ticket rejected');
$_SERVER = array_merge($edge, ['HTTP_HOST'=>ADMIN_DEVICE_RP,'HTTP_ORIGIN'=>ADMIN_DEVICE_ORIGIN,'REQUEST_METHOD'=>'POST']);
check(!adminAuthorized(), 'missing server session denied');
$_SESSION['admin_until'] = time() + 600;
$_SESSION['admin_network'] = ADMIN_DEVICE_NETWORK;
$_SESSION['admin_credential'] = adminCredentialDigest();
check(adminAuthorized(), 'verified session accepted');
$_SERVER['HTTP_X_L8_RENDER_CF_IP'] = '38.196.115.161';
check(adminAuthorized(), 'verified session survives authorized network rotation');
foreach (['38.196.115.0','38.196.115.73','38.196.115.128','38.196.115.161','38.196.115.255'] as $ip) check(adminIpAllowed($ip), 'allowed network address '.$ip);
foreach (['38.196.114.255','38.196.116.0','138.196.115.73','::ffff:38.196.115.73','38.196.115.073','38.196.115.73.attacker','38.196.115.256',''] as $ip) check(!adminIpAllowed($ip), 'outside or malformed address '.$ip);
$_SESSION['admin_network'] = '38.196.115.73';
check(!adminAuthorized(), 'old policy session rejected');
$_SESSION['admin_network'] = ADMIN_DEVICE_NETWORK;
$_SERVER['HTTP_X_L8_RENDER_CF_IP'] = '192.0.2.1';
check(!adminAuthorized(), 'session rejected after IP change');
$_SERVER['HTTP_X_L8_RENDER_CF_IP'] = '38.196.115.73';
$_SESSION['admin_until'] = time() - 1;
check(!adminAuthorized(), 'expired session rejected');
$_SESSION['admin_until'] = time() + 600;
$_SESSION['admin_credential'] = 'client-side-flag';
check(!adminAuthorized(), 'wrong enrolled credential rejected');
$_SESSION = []; session_destroy();
echo "PASS: $count checks\n";
