<?php
$pageTitle = 'Clientes | Hashcod Codespace';
$pageDescription = 'Hashcod Codespace para clientes, creadores, estudiantes, negocios y desarrolladores que necesitan convertir ideas en plataformas digitales.';
$canonical = 'https://hashcodcodespace.dev/clients';
$segments = [
  ['name'=>'Emprendedores','text'=>'Landing pages, formularios, dominios, SEO base y sistemas simples para vender o presentar servicios.'],
  ['name'=>'Desarrolladores','text'=>'Herramientas, auditoría, automatización, documentación y despliegue de proyectos técnicos.'],
  ['name'=>'Estudiantes','text'=>'Organización de proyectos, documentación, prototipos, prácticas técnicas y plataformas educativas.'],
  ['name'=>'Negocios locales','text'=>'Presencia digital, páginas de servicios, catálogos, contacto y confianza pública.'],
  ['name'=>'Creadores digitales','text'=>'Publicación de ideas, recursos, modelos, archivos, páginas de marca y sistemas de entrega.'],
  ['name'=>'Equipos técnicos','text'=>'Rutas seguras, despliegue, Supabase/Postgres, estado público y mejoras de producción.']
];
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= htmlspecialchars($pageTitle, ENT_QUOTES, 'UTF-8') ?></title><meta name="description" content="<?= htmlspecialchars($pageDescription, ENT_QUOTES, 'UTF-8') ?>"><link rel="canonical" href="<?= htmlspecialchars($canonical, ENT_QUOTES, 'UTF-8') ?>"><meta property="og:title" content="<?= htmlspecialchars($pageTitle, ENT_QUOTES, 'UTF-8') ?>"><meta property="og:description" content="<?= htmlspecialchars($pageDescription, ENT_QUOTES, 'UTF-8') ?>"><meta property="og:url" content="<?= htmlspecialchars($canonical, ENT_QUOTES, 'UTF-8') ?>"><meta property="og:type" content="website"><link rel="stylesheet" href="/components/hashcod-public-pages.css?v=20260922a"></head>
<body><div class="hc-page"><div class="hc-shell"><nav class="hc-nav"><a class="hc-brand" href="/"><span class="hc-mark">H</span><span><strong>Hashcod</strong><span>codespace</span></span></a><div class="hc-links"><a href="/services">Servicios</a><a href="/pricing">Precios</a><a href="/clients">Clientes</a><a href="/status">Estado</a><a href="/privacy">Privacidad</a></div></nav><main><section class="hc-hero"><div><span class="hc-kicker">Soluciones para distintos perfiles</span><h1 class="hc-title">Clientes que necesitan sistemas.</h1><p class="hc-lead">Hashcod Codespace está pensado para convertir necesidades reales en herramientas web, páginas, paneles, registros, documentación y presencia digital pública.</p><div class="hc-actions"><a class="hc-btn primary" href="/services">Explorar servicios</a><a class="hc-btn" href="/pricing">Ver precios</a></div></div><aside class="hc-panel"><h2>Enfoque</h2><ul class="hc-list"><li>Construir rápido sin perder orden.</li><li>Publicar con dominio, SSL y sitemap.</li><li>Mejorar diseño móvil y experiencia.</li><li>Proteger rutas internas antes de escalar.</li></ul></aside></section><section class="hc-section"><div class="hc-section-head"><h2>Perfiles</h2><p>Cada perfil puede tener un flujo diferente.</p></div><div class="hc-grid"><?php foreach($segments as $s): ?><article class="hc-card"><span class="hc-badge"><?= htmlspecialchars($s['name']) ?></span><h3><?= htmlspecialchars($s['name']) ?></h3><p><?= htmlspecialchars($s['text']) ?></p></article><?php endforeach; ?></div></section></main><footer class="hc-footer">© <?= date('Y') ?> Hashcod Codespace · Created by diktatcart · Hecho por Emil Enmanuel Pieter Mora</footer></div></div></body></html>
