<?php
declare(strict_types=1);

/** Public policy content, separate from previously accepted registration evidence. */
function hashcodDataProcessingAddendum(): array
{
    return [
        'title' => 'Licencia de procesamiento de datos y acuerdo de tratamiento (DPA)',
        'version' => '2026.10.08-1',
        'published_date' => '8 de octubre de 2026',
        'summary' => 'Autorización limitada para operar el servicio. El Usuario conserva sus derechos sobre los archivos; los datos de contacto de las solicitudes de tokenización se consultan en un área privada.',
        'sections' => [
            ['id' => 'partes', 'title' => '1. Partes, alcance y relación con la política', 'paragraphs' => [
                'El proveedor es Emil Enmanuel Pieter Mora, persona física comerciante que opera DIKTATCART y Hashcod Codespace, con RNC 402-0936929-3 y Registro Mercantil 3323LV-PF, en La Vega, República Dominicana. El Cliente o Usuario es la persona o entidad identificada en el acuerdo, registro o solicitud de servicio correspondiente; su representante debe contar con autorización suficiente.',
                'Este anexo adapta la plantilla Data Processing Addendum suministrada para los servicios de almacenamiento, edición, gestión de archivos y solicitudes de tokenización de Hashcod Codespace. Complementa Use and Privacy Policy y el acuerdo del servicio en materia de datos. Las normas imperativas de protección de datos y del consumidor prevalecen.',
                'La fecha de publicación identifica esta versión. La visita a la página, la selección de un plazo de acceso o una aceptación anterior no equivalen a aceptar retroactivamente este nuevo anexo. Su incorporación contractual requiere una aceptación expresa que identifique esta versión, o un acuerdo escrito o electrónico que la incorpore. No se declara que exista una firma certificada ni una aceptación registrada por el solo hecho de mostrarlo.',
            ]],
            ['id' => 'definiciones', 'title' => '2. Definiciones y funciones de las partes', 'bullets' => [
                'Datos personales: información que identifica o hace identificable a una persona, incluidos teléfono, correo, identificadores y datos personales contenidos en archivos. Los contactos profesionales también pueden ser datos personales.',
                'Datos del Cliente: archivos, documentos, código, contenido del editor e información entregados lícitamente para ejecutar el servicio. Tratamiento: recepción, almacenamiento, organización, consulta, transmisión autorizada, devolución y eliminación de esos datos.',
                'Responsable: quien decide los fines y medios del tratamiento. Encargado: quien trata datos por cuenta y bajo instrucciones del responsable. Subencargado: proveedor contratado para ejecutar parte de ese tratamiento.',
                'Hashcod actúa como encargado respecto de datos de terceros que el Cliente aporta para un servicio por su cuenta. El Cliente actúa como responsable o, si corresponde, como encargado autorizado por otro responsable. Hashcod actúa como responsable respecto de sus propias finalidades de contacto, administración de solicitudes, seguridad y obligaciones legales; no se confunden estas funciones.',
                'Incidente de seguridad: destrucción, pérdida, alteración, divulgación o acceso no autorizado que afecte datos personales. Un intento fallido sin compromiso de datos no constituye por sí solo una brecha de datos personales.',
            ]],
            ['id' => 'licencia', 'title' => '3. Licencia limitada e instrucciones del Cliente', 'paragraphs' => [
                'Cuando se incorpore este anexo al servicio, el Usuario concede a Hashcod una autorización no exclusiva, limitada a su finalidad y duración, para recibir, reproducir técnicamente, almacenar, presentar, organizar y procesar el contenido necesario para ejecutar las instrucciones del servicio. La autorización permite copias técnicas y acceso de proveedores estrictamente necesarios, sujetos a las salvaguardas de este anexo.',
                'El Usuario conserva la titularidad y los derechos que legítimamente tenga sobre sus archivos. La autorización no permite vender sus datos personales, publicar el contenido privado, ceder la propiedad de sus obras ni utilizarlo para una finalidad independiente. Las licencias de código y los derechos de terceros continúan vigentes.',
                'Las instrucciones se documentan mediante el acuerdo, la solicitud y las operaciones que el Usuario ejecuta, como cargar, editar, descargar, eliminar o solicitar revisión. Un encargo adicional, un nuevo destinatario o una finalidad incompatible requiere una instrucción y, cuando proceda, autorización separadas. Hashcod informará de instrucciones que considere contrarias a la normativa aplicable y podrá suspender ese tratamiento hasta aclararlas.',
                'El Usuario puede solicitar la terminación del encargo o retirar un consentimiento cuando este sea la base jurídica. Ello no invalida tratamientos anteriores lícitos ni impide conservar la información estrictamente necesaria por una obligación legal. No se autoriza el uso de archivos para entrenamiento de IA mediante esta licencia.',
            ]],
            ['id' => 'finalidades', 'title' => '4. Finalidades, datos de contacto y tokenización', 'paragraphs' => [
                'Hashcod trata los datos necesarios para prestar la función solicitada, conservar y recuperar archivos, mantener el espacio de trabajo, atender consultas, revisar solicitudes, prevenir abuso y cumplir obligaciones legales. La base jurídica se determina para cada finalidad conforme a la ley aplicable: ejecución del servicio, obligación legal o consentimiento cuando sea exigible; no se presume que una sola autorización cubra toda actividad.',
                'Al solicitar tokenización se guardan el teléfono y correo introducidos, el identificador de la solicitud, el archivo de referencia, nombre, tipo, tamaño, valor declarado si existe, fecha, período de acceso asociado y estado pendiente. El código del archivo se verifica para autorizar la operación y no se copia a la tabla de solicitudes. El teléfono y correo sirven para gestionar y dar seguimiento a la petición; no autorizan publicidad ni venta de datos.',
                'El envío inicia una solicitud de revisión. No produce automáticamente un token de blockchain, una certificación jurídica de autoría, una aprobación ni un mensaje por correo o SMS. Los datos de contacto se consultan en el área privada de solicitudes mediante acceso administrativo verificado en el servidor.',
            ]],
            ['id' => 'visibilidad', 'title' => '5. Visibilidad del espacio compartido y edición local', 'paragraphs' => [
                'Files utiliza un listado compartido de archivos. Otros usuarios con acceso a la plataforma pueden consultar metadatos como nombre, tipo, tamaño, fecha y valor declarado. El contenido del archivo requiere el código elegido al cargarlo para las operaciones protegidas. Este espacio no constituye una carpeta privada por cuenta; el Usuario debe evitar datos personales o secretos en nombres de archivo y metadatos compartidos.',
                'El editor y el estado sincronizado pueden pertenecer al espacio compartido de la plataforma. No deben utilizarse para introducir información confidencial de terceros sin autorización y sin comprobar la visibilidad de la función. Las solicitudes de tokenización y sus contactos se mantienen en un registro privado separado del listado compartido.',
                'La edición de escritorio puede conservar datos en el equipo y utilizar los mismos servicios en la nube para sincronización y solicitudes. Su instalación no convierte automáticamente todas las funciones en locales o sin conexión. El Usuario controla la seguridad de su dispositivo y las copias que exporte.',
            ]],
            ['id' => 'seguridad', 'title' => '6. Seguridad y confidencialidad', 'paragraphs' => [
                'Hashcod mantendrá medidas técnicas y organizativas proporcionadas a la naturaleza del servicio y al riesgo, según el Anexo 4. Las personas autorizadas deberán acceder únicamente cuando sea necesario para ejecutar el encargo y estar sujetas a obligaciones de confidencialidad.',
                'Las medidas se podrán actualizar para mantener o mejorar la protección. No se promete riesgo cero, aislamiento por cuenta donde no existe, cifrado de extremo a extremo de todas las funciones ni una certificación SOC 2 o ISO que no haya sido acreditada. Las firmas criptográficas y los códigos de acceso no sustituyen las demás obligaciones de privacidad.',
            ]],
            ['id' => 'incidentes', 'title' => '7. Incidentes y colaboración', 'paragraphs' => [
                'Al conocer un incidente que afecte datos personales tratados por cuenta del Cliente, Hashcod le informará sin dilación indebida por el contacto disponible, indicando la naturaleza del incidente, datos y personas potencialmente afectados, consecuencias previsibles y medidas de contención, en la medida en que se conozcan. La información podrá completarse por etapas.',
                'Hashcod colaborará razonablemente en la investigación, recuperación y atención de requerimientos. Cada parte atenderá las obligaciones de notificación que le correspondan según su función y la normativa aplicable. La coordinación entre las partes no retrasará plazos legales ni condicionará una notificación obligatoria a la autorización de la otra parte.',
            ]],
            ['id' => 'derechos', 'title' => '8. Derechos y canal de privacidad', 'paragraphs' => [
                'El titular puede solicitar acceso, rectificación, actualización, supresión o cancelación y oposición, además de otros derechos reconocidos por la norma aplicable. Una retirada de consentimiento no elimina las bases jurídicas que legítimamente correspondan a otros tratamientos.',
                'El canal publicado de Hashcod es WhatsApp +1 829 472 1257. Indique que se trata de una solicitud de privacidad, la función o número de solicitud afectado y un medio de respuesta. No envíe contraseñas, claves administrativas, códigos de archivos, documentos completos ni información sensible por ese canal inicial. Hashcod solicitará únicamente la verificación proporcional de identidad o representación necesaria y coordinará un medio adecuado para intercambiar información.',
                'Si Hashcod actúa como encargado, trasladará la petición al Cliente responsable y le prestará asistencia razonable; si actúa como responsable, tramitará la solicitud directamente. Las respuestas respetarán los plazos y límites legales. La falta de una cuenta individual no elimina los derechos del titular ni permite entregar datos de terceros sin verificación.',
            ]],
            ['id' => 'cliente', 'title' => '9. Obligaciones del Cliente y datos restringidos', 'paragraphs' => [
                'El Cliente debe disponer de base jurídica, derechos sobre el material, avisos y autorizaciones necesarias antes de aportar datos de terceros. Debe minimizar los datos, corregir inexactitudes, proteger su dispositivo y sus códigos, y conservar las copias que necesite. Estas responsabilidades no eximen a Hashcod de las obligaciones que le correspondan.',
                'Las funciones ordinarias de Files, editor y solicitudes no están destinadas a historiales médicos, biometría, datos financieros o de tarjetas, contraseñas ajenas, claves privadas, expedientes fiscales, categorías especialmente protegidas ni datos personales de menores. Su tratamiento requiere un acuerdo previo y salvaguardas adecuadas. La cédula solicitada en un registro específico se rige por ese procedimiento y su finalidad; no debe repetirse dentro de archivos o metadatos compartidos.',
                'El servicio exige que la persona que contrata tenga al menos dieciocho años y capacidad de representación. La inclusión de datos de otras personas requiere una evaluación separada de su licitud, aunque quien opere la herramienta sea mayor de edad.',
            ]],
            ['id' => 'proveedores', 'title' => '10. Subencargados y cambios de proveedores', 'paragraphs' => [
                'Los proveedores identificados en el Anexo 5 intervienen solamente en las funciones descritas. Hashcod deberá establecer las obligaciones contractuales de protección, confidencialidad y seguridad necesarias antes de confiarles un encargo sujeto a este DPA, y seguirá respondiendo por las obligaciones que delegue en la medida exigida por la ley.',
                'Cuando el Cliente autorice de manera general el uso de subencargados en un encargo aceptado, Hashcod informará de nuevas incorporaciones o sustituciones relevantes por esta lista y por un medio escrito disponible, con al menos quince días de antelación salvo urgencia legal o de seguridad justificada. El Cliente podrá objetar por motivos razonables de protección de datos; las partes buscarán una alternativa o acordarán el cese de la función afectada, preservando los derechos legales del Cliente.',
                'Un repositorio o una biblioteca de software no constituye por sí solo un subencargado. Requests es el cliente HTTP usado por el backend y no recibe datos en un servicio propio por el hecho de estar instalado.',
            ]],
            ['id' => 'transferencias', 'title' => '11. Ubicación y transferencias internacionales', 'paragraphs' => [
                'La infraestructura de nube puede procesar datos fuera de la República Dominicana. Las ubicaciones operativas conocidas se identifican en el Anexo 5; el soporte y la infraestructura de un proveedor pueden requerir otras ubicaciones conforme a su documentación y al contrato aplicable. Las partes deberán comprobar la base y las garantías necesarias para cada transferencia.',
                'La publicación de este anexo no firma automáticamente cláusulas contractuales tipo europeas, un anexo británico ni instrumentos suizos. Si una transferencia los exige, deberán completarse y acordarse sus datos, módulos, medidas y garantías antes de efectuarla, conforme al Anexo 2. Una mención al GDPR no certifica cumplimiento universal ni sustituye ese análisis.',
            ]],
            ['id' => 'auditorias', 'title' => '12. Información, evaluación y auditorías', 'paragraphs' => [
                'Hashcod facilitará información razonablemente necesaria para acreditar las obligaciones del encargo y colaborará en auditorías proporcionadas. Una auditoría ordinaria podrá coordinarse una vez al año, con aviso de catorce días, alcance definido y confidencialidad; ese límite no impedirá actuaciones adicionales requeridas por ley, por una autoridad competente o por un incidente relevante.',
                'Las verificaciones no deberán revelar datos de otros usuarios, claves, secretos comerciales o información que debilite la seguridad. Se acordarán medios alternativos cuando sea necesario. Los costes de trabajo extraordinario se comunicarán y acordarán previamente, sin convertirlos en una barrera a derechos u obligaciones legales.',
            ]],
            ['id' => 'conservacion', 'title' => '13. Duración, devolución y eliminación', 'paragraphs' => [
                'El tratamiento por encargo dura mientras se presta la función solicitada y durante el tiempo estrictamente necesario para su cierre, devolución o eliminación. Hashcod limitará la conservación a finalidades justificadas y obligaciones legales, manteniendo la protección durante ese período.',
                'El plazo de acceso elegido en la plataforma limita la sesión; su vencimiento no ejecuta una eliminación automática de archivos, del editor ni de solicitudes. Eliminar el archivo fuente tampoco elimina por sí solo la solicitud de tokenización: esta conserva su referencia y datos de contacto. Para solicitar la eliminación de ese registro o el cierre del encargo, utilice el canal de privacidad.',
                'Al terminar el encargo, el Cliente podrá solicitar devolución por un medio seguro o supresión de los datos tratados por su cuenta, salvo conservación legal obligatoria. Hashcod comunicará el alcance de la actuación y cualquier excepción justificada. Las copias de seguridad, si existen, quedarán restringidas hasta su eliminación conforme al ciclo aplicable; las copias exportadas y los datos en dispositivos del Usuario están bajo su control.',
            ]],
            ['id' => 'ia', 'title' => '14. Inteligencia artificial y decisiones automatizadas', 'paragraphs' => [
                'La solicitud de tokenización no envía automáticamente el archivo a una IA. El chat de revisión, iniciado expresamente por el Usuario, utiliza Anthropic con su propia API key y el modelo permitido que seleccione. Antes de iniciar se muestran el proveedor, el presupuesto máximo y la autorización para enviar el archivo y los mensajes necesarios. No se envían el teléfono, correo ni la clave como parte del prompt.',
                'La API key se valida mediante una petición que no genera respuestas, se conserva cifrada solo en memoria durante un máximo de 30 minutos y se elimina al finalizar o cerrar la revisión. Un reinicio del servicio exige introducirla de nuevo. Los mensajes, comprobaciones, huella SHA-512, modelo y certificados se guardan en un registro privado para seguimiento. El certificado público contiene una huella y alcance técnico, sin contactos ni contenido del archivo; puede revocarse y deja de ser válido si el archivo cambia o desaparece.',
                'El código se analiza en un servicio separado. La ejecución de pruebas del Usuario ocurre únicamente dentro de WebAssembly sin permisos de red o de escritura en los archivos montados. Las comprobaciones incompletas o de dependencias externas requieren revisión humana. Un certificado identifica la versión y el alcance revisados; no garantiza la ausencia de defectos, titularidad, valor comercial ni cumplimiento legal. WhatsApp solo se abre cuando el Usuario pulsa el enlace después de una verificación válida.',
                'Hashcod no utilizará datos personales para entrenar o ajustar modelos propios o ajenos sin una autorización separada, específica y válida. Antes de utilizar un proveedor de IA para datos del Cliente, deberá establecer condiciones que impidan el entrenamiento independiente no autorizado. Una posibilidad de uso descrita por un proveedor no se presenta como una garantía verificada de Hashcod.',
                'La revisión o tokenización no equivale a una decisión automática de efectos jurídicos o similares sobre una persona. Si se ofrece una función con esos efectos, deberán comunicarse su lógica y consecuencias en la medida legalmente exigible y habilitarse las garantías y revisión humana correspondientes antes de su uso.',
            ]],
            ['id' => 'condiciones', 'title' => '15. Modificaciones, responsabilidad y ley aplicable', 'paragraphs' => [
                'Este anexo mantiene su propia versión y huella de integridad. Los cambios materiales en finalidades, destinatarios o compromisos deberán comunicarse y requerirán una nueva aceptación cuando corresponda; no sustituyen la evidencia de versiones previamente aceptadas.',
                'Se aplica la legislación de la República Dominicana, incluida la Ley núm. 172-13, sin excluir normas imperativas extranjeras que alcancen el tratamiento concreto. Las limitaciones del acuerdo principal solo operan en la medida permitida por la ley; no eliminan derechos de los titulares, obligaciones del consumidor ni responsabilidades que no puedan limitarse.',
                'Si una cláusula es inválida, las restantes conservarán su alcance lícito. Las garantías exigidas por una norma imperativa o por un instrumento de transferencia válidamente acordado prevalecerán ante una incompatibilidad.',
            ]],
        ],
        'annexes' => [
            ['id' => 'anexo-1', 'title' => 'Anexo 1 · Detalles del tratamiento', 'bullets' => [
                'Proveedor: Emil Enmanuel Pieter Mora / DIKTATCART / Hashcod Codespace, La Vega, República Dominicana. Contacto de privacidad: WhatsApp +1 829 472 1257. Cliente: persona o entidad y representante identificados en el acuerdo o solicitud; los datos y domicilio necesarios para un encargo formal se documentarán antes de su aceptación.',
                'Interesados: el Usuario, sus representantes y las personas cuyos datos aporte lícitamente. Datos: archivos y contenido autorizado; metadatos; contacto; identificadores de solicitud, sesión o dispositivo y registros técnicos necesarios para seguridad. No se autoriza por defecto el tratamiento de las categorías restringidas de la sección 9.',
                'Operaciones y finalidad: recepción, almacenamiento, sincronización, edición y recuperación solicitadas; revisión de tokenización y seguimiento. Frecuencia: cuando el Usuario inicia la operación y mientras sea necesario para el servicio. Duración: según la sección 13 y el acuerdo del encargo.',
                'Funciones: Cliente responsable o encargado autorizado; Hashcod encargado para el contenido tratado por cuenta del Cliente y responsable para sus finalidades propias de operación, contacto y seguridad. Destinatarios técnicos: únicamente los aplicables del Anexo 5 y los que se autoricen conforme a la sección 10.',
            ]],
            ['id' => 'anexo-2', 'title' => 'Anexo 2 · Europa, Reino Unido y Suiza', 'paragraphs' => [
                'Este anexo se aplica únicamente cuando el tratamiento esté sujeto al GDPR de la Unión Europea, al régimen de protección de datos del Reino Unido o a la legislación suiza. Hashcod prestará la asistencia exigible para derechos, seguridad, evaluaciones de impacto y consultas a autoridades en relación con el encargo.',
                'Antes de una transferencia restringida, las partes evaluarán su licitud y, cuando proceda, formalizarán las cláusulas contractuales tipo de la Decisión (UE) 2021/914: módulo 2 para responsable a encargado o módulo 3 para encargado a subencargado, según las funciones reales. Para Reino Unido o Suiza se acordarán el instrumento y las adaptaciones vigentes que correspondan.',
                'Se deberán documentar las partes, domicilios y contactos, autoridad competente, ley y tribunal correspondientes, categorías y operaciones, medidas, subencargados y evaluación de transferencia. Esta página no da por completados ni firmados esos instrumentos, no selecciona por defecto un tribunal extranjero y no sustituye sus cláusulas obligatorias.',
            ]],
            ['id' => 'anexo-3', 'title' => 'Anexo 3 · Leyes estatales de privacidad de Estados Unidos', 'paragraphs' => [
                'Cuando una ley estatal aplicable trate a Hashcod como proveedor de servicios, contratista o encargado, los datos se usarán para los fines concretos autorizados y con la protección que dicha norma exija. No se venderán ni compartirán para publicidad conductual entre contextos; tampoco se combinarán con datos de otros clientes o finalidades independientes salvo una excepción legal válida.',
                'Hashcod notificará si no puede cumplir una obligación aplicable y colaborará en medidas proporcionadas para detener y corregir un tratamiento no autorizado. El Cliente podrá verificar el encargo conforme a la sección 12. Este apartado no presume que todas las leyes estatales sean aplicables a todos los usuarios.',
            ]],
            ['id' => 'anexo-4', 'title' => 'Anexo 4 · Medidas de seguridad y límites operativos', 'bullets' => [
                'Transporte HTTPS en la plataforma alojada y verificación de certificados en las llamadas del backend. La edición de escritorio utiliza un servicio local de loopback y HTTPS para los servicios de nube.',
                'Verificación del código para las operaciones protegidas de archivos. Registro privado de solicitudes separado del listado compartido, con seguridad por filas y sin permisos de lectura para usuarios anónimos o autenticados ordinarios.',
                'Clave administrativa verificada en servidor; sesiones privadas limitadas, cookies HttpOnly y SameSite, comprobación de origen, límites de intentos y de tamaño de entrada. Las claves no deben publicarse ni incluirse en archivos del Cliente.',
                'Validación de datos de contacto y de metadatos, controles frente a inyección y manejo de errores que evite divulgar secretos. Se limita la exposición del contenido mediante las rutas y autorizaciones de cada función.',
                'Confidencialidad y mínimo acceso necesario para quien atienda el encargo; revisión de cambios, dependencias, incidentes y permisos. No se atribuyen auditorías externas, respaldo garantizado ni cifrado integral a funciones donde no se hayan acreditado.',
                'Límite conocido: Files y el estado compartido no aíslan por cuenta los metadatos o todo contenido de edición. Los códigos de archivos y el área privada de contactos protegen funciones diferentes, como explica la sección 5.',
            ]],
            ['id' => 'anexo-5', 'title' => 'Anexo 5 · Proveedores y ubicaciones operativas', 'paragraphs' => [
                'La siguiente lista refleja la configuración conocida al publicar esta versión. No afirma que cada proveedor intervenga en todas las operaciones ni sustituye sus condiciones contractuales o los instrumentos de transferencia exigibles.',
            ], 'table' => [
                'headers' => ['Proveedor', 'Función y datos', 'Ubicación / condición'],
                'rows' => [
                    ['Supabase', 'Base de datos, almacenamiento y funciones de nube para archivos, estado y solicitudes; contenido y metadatos necesarios para esas funciones.', 'Proyecto configurado en Estados Unidos, región us-east-1.'],
                    ['Railway', 'Alojamiento de la aplicación y ejecución del backend; solicitudes HTTP y registros técnicos asociados al servicio.', 'Servicio alojado en Estados Unidos, región sfo, al publicar esta versión.'],
                    ['Cloudflare, cuando esté activado', 'Servicios configurados de red y protección, incluidos desafíos Turnstile; señales técnicas y de seguridad de la conexión.', 'Infraestructura distribuida; depende de la función y configuración activas.'],
                    ['WhatsApp / Meta, si el Usuario utiliza el canal', 'Comunicación directa de soporte y privacidad; recibe el mensaje y datos del remitente bajo sus propias condiciones.', 'Servicio de comunicación de terceros; su uso no exige enviar archivos sensibles ni claves.'],
                    ['Anthropic (chat de revisión solicitado)', 'Código del archivo seleccionado, preguntas y comprobaciones necesarias. API key del Usuario únicamente como credencial del transporte HTTPS; nunca en el prompt.', 'Procesamiento según las condiciones de la API de Anthropic y la configuración de su cuenta. El Usuario debe comprobar que está autorizado a enviar ese contenido.'],
                ],
            ]],
        ],
        'references' => [
            ['label' => 'Ley núm. 172-13 · Protección de datos personales (fuente legislativa dominicana)', 'url' => 'https://camaradediputados.gob.do/transparencia/marco-legal/leyes/'],
            ['label' => 'Reglamento (UE) 2016/679 · GDPR, especialmente artículos 28 y 32 y capítulo V, cuando resulte aplicable', 'url' => 'https://eur-lex.europa.eu/eli/reg/2016/679/oj'],
        ],
        'attribution' => 'Adaptación de la plantilla Data Processing Addendum de General Legal, PC suministrada por el Usuario. General Legal no ha revisado ni avalado esta adaptación; su plantilla no crea una relación abogado-cliente ni acredita la conformidad de esta plataforma. Las cláusulas se han ajustado a las funciones y límites descritos de Hashcod Codespace.',
    ];
}

function hashcodDataProcessingAddendumSha256(): string
{
    return hash('sha256', json_encode(hashcodDataProcessingAddendum(), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR));
}
