'use strict';

const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const repoDir = path.resolve(__dirname, '../..');
const js = fs.readFileSync(path.join(repoDir, 'components/efr-code-editor.js'), 'utf8');
const css = fs.readFileSync(path.join(repoDir, 'components/efr-code-editor.css'), 'utf8');
const hosted = fs.readFileSync(path.join(repoDir, 'l8-html.php'), 'utf8');
const local = fs.readFileSync(path.join(repoDir, 'laragon-local-entry.php'), 'utf8');

assert(js.includes("const TOOL_ID = 'efr-code-editor'"), 'EFT editor tool id missing');
assert(js.includes('const TRAY_SLOT = 4'), 'EFT editor must occupy the fifth tray cube (slot 4)');
assert(js.includes("label: 'EFT CoffeeScript Notebook'"), 'EFT editor tray label missing');
assert(js.includes("const EFT_FORMAT = 'HASHCOD-EFT-1'"), 'HASHCOD-EFT-1 format marker missing');
assert(js.includes('const MODEL_VERSION = 3'), 'algorithm-profile EFT model version missing');
assert(js.includes('const NBFORMAT_MAJOR = 4'), 'Jupyter nbformat major version missing');
assert(js.includes('const NBFORMAT_MINOR = 5'), 'Jupyter nbformat minor 4.5 target missing');
assert(js.includes("const CELL_SEPARATOR = '# %% [EFT CELL]'"), 'CoffeeScript notebook cell separator missing');

assert(js.includes("const ALGORITHM_PROFILE = 'THEALGORITHMS-JUPYTER-1'"), 'TheAlgorithms/Jupyter profile marker missing');
assert(js.includes("const ALGORITHM_REFERENCE = 'https://github.com/TheAlgorithms/Jupyter'"), 'TheAlgorithms/Jupyter source reference missing');
assert(js.includes("'commented_source'"), 'commented source algorithm requirement missing');
assert(js.includes("'readable_naming'"), 'readable naming algorithm requirement missing');
assert(js.includes("'math_explanation'"), 'math explanation algorithm requirement missing');
assert(js.includes("'notebook_demo'"), 'notebook demo algorithm requirement missing');
assert(js.includes('function algorithmTemplateNotebook()'), 'algorithm notebook template missing');
assert(js.includes('function algorithmReport(notebook)'), 'algorithm structure checker missing');
assert(js.includes("algorithm_role: 'definition'"), 'definition role missing');
assert(js.includes("algorithm_role: 'implementation'"), 'implementation role missing');
assert(js.includes("algorithm_role: 'demo'"), 'demo role missing');
assert(js.includes('# Math: Describe the formula'), 'math explanation template missing');
assert(js.includes('solveAlgorithm = (inputValue) ->'), 'CoffeeScript algorithm implementation template missing');
assert(js.includes('# DEMO'), 'algorithm demo template missing');
assert(js.includes('New Algorithm'), 'new algorithm action missing');
assert(js.includes('Check Algorithm'), 'algorithm checker action missing');
assert(js.includes('Definition/Math → Implementation → Demo'), 'algorithm workflow must be visible in the editor');

assert(js.includes('class EftNotebookModel'), 'structured EFT notebook model missing');
assert(js.includes('toJSON()'), 'NotebookModel-style toJSON serialization missing');
assert(js.includes('fromJSON(value, options = {})'), 'NotebookModel-style fromJSON deserialization missing');
assert(js.includes('toString()'), 'NotebookModel-style toString serialization missing');
assert(js.includes('fromString(value, options)'), 'NotebookModel-style fromString deserialization missing');
assert(js.includes('replaceSources(sources, options = {})'), 'cell source synchronization model missing');
assert(js.includes('insertCell(index, source = '), 'structured cell insertion missing');
assert(js.includes('deleteCell(index)'), 'structured cell deletion missing');
assert(js.includes('moveCell(fromIndex, toIndex)'), 'structured cell move missing');
assert(js.includes('deletedCells'), 'deleted cell tracking missing');
assert(js.includes('this.dirty = true'), 'dirty document state missing');
assert(js.includes('markClean()'), 'clean document state transition missing');
assert(js.includes('function cellId()'), 'nbformat 4.5 cell ID generation missing');
assert(js.includes('validId'), 'cell ID validation missing');
assert(js.includes("jupyterlab_model_reference: 'packages/notebook/src/model.ts'"), 'JupyterLab model reference metadata missing');
assert(js.includes("execution_policy: 'disabled'"), 'EFT must explicitly disable execution');
assert(js.includes('trusted: false'), 'created/imported EFT cells must not be marked trusted');
assert(js.includes("codemirror_mode: 'coffeescript'"), 'CoffeeScript editor metadata missing');
assert(js.includes("name: 'coffeescript'"), 'CoffeeScript language metadata missing');
assert(js.includes("file_extension: '.coffee'"), 'CoffeeScript file extension metadata missing');
assert(js.includes("container: 'Jupyter Notebook'"), 'Jupyter Notebook container metadata missing');
assert(js.includes("cell_type: 'code'"), 'Jupyter code cell structure missing');
assert(js.includes('execution_count: null'), 'Jupyter execution_count structure missing');
assert(js.includes('outputs: []'), 'Jupyter outputs structure missing');
assert(js.includes('eft_source: true'), 'EFT CoffeeScript cell metadata missing');
assert(js.includes('function buildEftNotebook()'), 'EFT notebook serializer missing');
assert(js.includes('function notebookToCoffeeScript(notebook)'), 'IPYNB CoffeeScript importer missing');
assert(js.includes("importInput.accept = '.eft,.ipynb,.coffee,application/json,text/plain'"), 'only EFT/IPYNB/CoffeeScript import formats should be offered');
assert(js.includes("sanitizeName(name.value) + '.eft'"), 'downloads must use the .eft extension');
assert(js.includes('JSON.stringify(notebook, null, 2)'), 'EFT download must serialize notebook JSON');
assert(js.includes("type: 'application/json;charset=utf-8'"), 'EFT download must preserve notebook JSON payload');
assert(js.includes('data-language="coffeescript"'), 'editor must declare CoffeeScript language mode');
assert(js.includes('New Cell'), 'notebook cell insertion control missing');
assert(js.includes('Delete Cell'), 'notebook cell deletion control missing');
assert(js.includes('↑ Cell'), 'notebook cell move-up control missing');
assert(js.includes('↓ Cell'), 'notebook cell move-down control missing');
assert(js.includes('window.HashcodEftNotebookModel = EftNotebookModel'), 'EFT notebook model API must be exposed for testing/integration');
assert(js.includes('applyAlgorithmTemplate'), 'algorithm template API missing');
assert(js.includes('checkAlgorithm'), 'algorithm checker API missing');
assert(js.includes('algorithmReport'), 'algorithm report API missing');

assert(js.includes("document.createElement('dialog')"), 'EFT modal must use a native dialog/top-layer surface');
assert(js.includes("typeof modal.showModal === 'function'"), 'EFT modal must enter browser top layer when supported');
assert(js.includes('handlePhysicalTrayPress'), 'coordinate-based tray interaction rescue missing');
assert(js.includes("window.addEventListener('pointerdown', handlePhysicalTrayPress, true)"), 'window capture pointer rescue missing');
assert(js.includes('pointInsideButton'), 'tray rescue must work by physical coordinates');
assert(js.includes('button.disabled = false'), 'fifth tray cube must be actively repaired to enabled state');
assert(js.includes('button.onclick = function'), 'direct button click fallback missing');
assert(js.includes("const HOTZONE_ID = 'hashcodEfrHotzone'"), 'fixed click hotzone missing');
assert(js.includes('z-index:2147483646'), 'hotzone must sit above regular auth/tray stacking contexts');
assert(!js.includes('setInterval(repairAndSync, 400)'), 'EFT editor must not poll the main thread every 400ms');
assert(js.includes('function scheduleRepair()'), 'EFT repair work must be animation-frame batched');
assert(js.includes("document.visibilityState === 'hidden'"), 'EFT repair work must pause while the tab is hidden');
assert(js.includes('mutationTouchesTray'), 'EFT observer must ignore unrelated DOM mutations');
assert(js.includes('childList: true'), 'tray replacement observer missing');
assert(js.includes("document.documentElement.dataset.hashcodEfrReady = 'true'"), 'runtime readiness marker missing');
assert(js.includes("modal.style.setProperty('display', 'grid', 'important')"), 'editor open path must force visible display');
assert(!js.includes('eval('), 'editor must never execute user code');
assert(!js.includes('new Function('), 'editor must never compile user code');

assert(css.includes('dialog#hashcodEfrEditorModal'), 'native dialog styling missing');
assert(css.includes('dialog#hashcodEfrEditorModal::backdrop'), 'native dialog backdrop styling missing');
assert(css.includes('#hashcodEfrEditorTextarea'), 'editor textarea styling missing');
assert(hosted.includes('hashcod-efr-code-editor-inline'), 'hosted page must inline the current EFT implementation to bypass stale CDN cache');
assert(hosted.includes('components/efr-code-editor.js?v=20260919-perf1'), 'hosted JS fallback loader missing');
assert(local.includes('hashcod-laragon-efr-code-editor-inline'), 'local entry must inline the current EFT implementation');
assert(local.includes('components/efr-code-editor.js?v=20260919-perf1'), 'local JS fallback loader missing');

console.log('PASS: EFT keeps CoffeeScript/IPYNB 4.5 and adds a TheAlgorithms/Jupyter-inspired definition/math → implementation → demo algorithm profile without executing code.');