const fs=require('fs'),assert=require('assert');
const gate=fs.readFileSync('mldsa-access.php','utf8');
const api=fs.readFileSync('mldsa-access-api.php','utf8');
const css=fs.readFileSync('components/mldsa-access-gate.css','utf8');
const js=fs.readFileSync('components/mldsa-access-gate.js','utf8');
const l8=fs.readFileSync('l8-html.php','utf8');
const router=fs.readFileSync('router.php','utf8');
const req=fs.readFileSync('requirements-streamlit.txt','utf8');
const spotlightAsset=fs.readFileSync('components/mldsa-card-assets/spotlight-code.svg','utf8');
const pitAsset=fs.readFileSync('components/mldsa-card-assets/pit-barriers.svg','utf8');
const singleBedAsset=fs.readFileSync('components/mldsa-card-assets/single-bed-base.svg','utf8');
const tokenizedAsset=fs.readFileSync('components/mldsa-card-assets/tokenized-certification.svg','utf8');
const pubRaw=fs.readFileSync('config/mldsa87-access-public.b64','utf8');
const pub=pubRaw.replace(/\s+/g,'');
function crc32(str){let table=crc32.t;if(!table){table=crc32.t=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?(0xedb88320^(c>>>1)):(c>>>1);return c>>>0;});}let crc=0xffffffff;for(let i=0;i<str.length;i++)crc=table[(crc^str.charCodeAt(i))&255]^(crc>>>8);return (crc^0xffffffff)>>>0;}

assert.strictEqual(pub.length,3456,'ML-DSA-87 public key Base64 length must be exact');
assert(/^[A-Za-z0-9+/]+$/.test(pub),'ML-DSA-87 public key contains invalid Base64 characters');
assert.strictEqual(crc32(pub).toString(16).padStart(8,'0'),'25eb08f5','production ML-DSA-87 public key checksum mismatch');
assert.strictEqual(Buffer.from(pub,'base64').length,2592,'ML-DSA-87 public key must decode to 2592 bytes');

assert(gate.includes("strlen($sig)!==4627"),'signature length guard missing');
assert(gate.includes("HC-MLDSA87-V2.P1."),'phase-1 challenge prefix missing');
assert(gate.includes("HC-MLDSA87-V2.P2."),'phase-2 challenge prefix missing');
assert(gate.includes("function mldsaConsumeJti"),'atomic anti-replay JTI consumption missing');
assert(gate.includes("fopen($path,'x')"),'anti-replay store must use exclusive create');
assert(gate.includes("function mldsaOriginAllowed"),'same-origin request binding missing');
assert(gate.includes("phase1_proof"),'phase-2 challenge must bind phase-1 proof');
assert(gate.includes("parent_jti"),'phase-2 challenge must bind parent challenge');
assert(gate.includes("L8_ACCESS_MLDSA87_PHASE1_TTL"),'phase-1 TTL configuration missing');
assert(gate.includes("L8_ACCESS_MLDSA87_PHASE2_TTL"),'phase-2 TTL configuration missing');
assert(gate.includes("min(7200"),'access session maximum TTL cap missing');
assert(gate.includes("httponly'=>true"),'HttpOnly cookie missing');
assert(gate.includes("samesite'=>'Strict"),'SameSite Strict missing');
assert(gate.includes("function mldsaAccessRequired(): bool"),'required gate function missing');
assert(!gate.includes("if (!mldsaAccessConfigured()) return false;"),'gate must fail closed');

assert(api.includes("protocol'=>'ML-DSA-87-2PHASE"),'two-phase protocol marker missing');
assert(api.includes("replay_detected"),'replay rejection missing');
assert(api.includes("origin_mismatch"),'origin mismatch rejection missing');
assert(api.includes("phase_mismatch"),'phase mismatch rejection missing');
assert(api.includes("mldsaConsumeJti"),'API must consume one-time JTI');
assert(api.includes("securityIpStrike('mldsa_access_fail',3"),'progressive failure strike threshold missing');
assert(api.includes("securityIpIsBanned"),'IP temporary ban check missing');

assert(js.includes("Paso 1 de 2"),'phase-1 UI missing');
assert(js.includes("Paso 2 de 2"),'phase-2 UI missing');
assert(js.includes("next_phase"),'frontend phase transition missing');
assert(js.includes("phase:phase"),'frontend must bind submitted signature to current phase');
assert(css.includes(".security-progress{"),'two-phase progress UI missing');

assert(l8.includes('mldsaShouldGateHtml'),'HTML gate missing');
assert(router.includes("'/api/mldsa-access'"),'access route missing');
assert(req.includes('pqcrypto==1.0.0'),'pqcrypto pin missing');
assert(css.includes('max-width:380px'),'SpectrumUI compact card missing');
assert(css.includes('border-radius:24px'),'SpectrumUI card radius missing');
assert(gate.includes('id="d5ToolDeck"'),'animated tool deck missing');
assert(gate.includes('Spotlight Code'),'Spotlight Code card missing');
assert(gate.includes('Code focused on your custom enhancements, providing you with the necessary credentials to make fixes or changes.'),'Spotlight Code description missing');
assert(gate.includes('Pit Barriers'),'Pit Barriers card missing');
assert(gate.includes('Single bed base'),'Single bed base card missing');
assert(gate.includes('Tokenized certification'),'Tokenized certification card missing');
assert(gate.includes('Obtain your tokenized platform certification by integrating with our Codespace and contacting us.'),'Tokenized certification description missing');
assert(gate.includes('Rent out your unit through the CRM, and you can even sell or rent it to someone else.'),'Single bed base description missing');
assert(gate.includes('Barriers with intentional holes designed to lure your code into false traps.'),'Pit Barriers description missing');
assert(gate.includes('components/mldsa-card-assets/pit-barriers.svg'),'Pit Barriers asset missing from gate');
assert(gate.includes('components/mldsa-card-assets/single-bed-base.svg'),'Single bed base asset missing from gate');
assert(gate.includes('components/mldsa-card-assets/tokenized-certification.svg'),'Tokenized certification asset missing from gate');
assert(spotlightAsset.includes('M90,23.333L60,10'),'requested Spotlight Code SVG path missing');
assert(pitAsset.includes('M70,10H10v80h41.849'),'requested Pit Barriers SVG path missing');
assert(singleBedAsset.includes('M 50 10 C 33.431 10 20 15.969031'),'requested Single bed base SVG path missing');
assert(tokenizedAsset.includes('M 10 4 L 10 6 L 12 6'),'requested Tokenized certification SVG path missing');
assert(css.includes('width:320px'),'AnimatedCard must retain Spectrum UI 320px width');
assert(css.includes('width:128px')&&css.includes('height:128px'),'AnimatedCard logo must retain 128x128 size');
assert(css.includes('--x:-300px;--y:-65px;--rot:-20deg'),'card 1 expansion coordinates changed');
assert(css.includes('--x:-85px;--y:-120px;--rot:-10deg'),'card 2 expansion coordinates changed');
assert(css.includes('--x:150px;--y:-135px;--rot:5deg'),'card 3 expansion coordinates changed');
assert(css.includes('--x:340px;--y:-94px;--rot:17deg'),'card 4 expansion coordinates changed');
assert(js.includes('function setDeckExpanded'),'tool deck toggle logic missing');
assert(js.includes("deck.addEventListener('click'"),'tool deck click interaction missing');
assert(js.includes("deck.addEventListener('keydown'"),'tool deck keyboard interaction missing');
assert(gate.includes('id="d5FaqCard"'),'FAQTabsCard container missing');
assert(gate.includes('data-faq-tab="0"'),'FAQTabsCard tabs missing');
assert(gate.includes('id="d5FaqAccordion"'),'FAQTabsCard accordion missing');
assert(gate.includes('id="d5FaqFooter"'),'FAQTabsCard footer missing');
assert(css.includes('max-width:378px'),'FAQTabsCard must retain Spectrum UI 378px max width');
assert(css.includes('border-radius:26px'),'FAQTabsCard 26px radius missing');
assert(css.includes('height:36px'),'FAQTabsCard tab rail height missing');
assert(css.includes('height:27px'),'FAQTabsCard active tab height missing');
assert(css.includes('border-radius:18px'),'FAQTabsCard accordion 18px radius missing');
assert(css.includes('margin-top:25px'),'FAQTabsCard footer spacing missing');
assert(css.includes('position:absolute'),'desktop FAQ must be out of grid flow so animated cards keep their original position');
assert(css.includes('top:calc(100% + 32px)'),'desktop FAQ must stay anchored below the ML-DSA card');
assert(js.includes("label:'General'"),'FAQ General tab missing');
assert(js.includes('¿Qué obtengo al entrar a Hashcod Codespace?'),'General FAQ question 1 missing');
assert(js.includes('¿Qué puedo hacer dentro de Hashcod Codespace?'),'General FAQ question 2 missing');
assert(js.includes('¿Cómo funciona el proceso de validación de mi proyecto?'),'General FAQ question 3 missing');
assert(js.includes('Al entrar a Hashcod Codespace obtienes acceso a un entorno digital diseñado para trabajar, organizar y desarrollar tu proyecto desde un mismo espacio.'),'General FAQ answer 1 missing');
assert(js.includes('Dentro de Hashcod Codespace puedes utilizar diferentes herramientas para crear, organizar, desarrollar y gestionar tu proyecto digital desde un solo entorno.'),'General FAQ answer 2 missing');
assert(js.includes('Cuando envías la información de tu proyecto a través de Hashcod Codespace, se genera un registro asociado a tu solicitud.'),'General FAQ answer 3 missing');
assert(js.includes("label:'Building'"),'FAQ Building tab missing');
assert(js.includes('¿Por qué mi Toolbook está vacía cuando entro por primera vez?'),'Building FAQ question 1 missing');
assert(js.includes('¿Cómo solicito que Hashcod Codespace desarrolle una herramienta o función para mi proyecto?'),'Building FAQ question 2 missing');
assert(js.includes('¿Qué tipo de herramientas o funciones puedo solicitar que se desarrollen?'),'Building FAQ question 3 missing');
assert(js.includes('Cuando accedes por primera vez a Hashcod Codespace, tu Toolbook estará vacía por defecto.'),'Building FAQ answer 1 missing');
assert(js.includes('Para solicitar una nueva herramienta, función o módulo, debes enviar una petición de desarrollo a Hashcod Codespace'),'Building FAQ answer 2 missing');
assert(js.includes('En Hashcod Codespace puedes solicitar el desarrollo de herramientas, funciones o módulos adaptados a las necesidades de tu proyecto.'),'Building FAQ answer 3 missing');
assert(js.includes("label:'Goals'"),'FAQ Goals tab missing');
assert(js.includes('¿Para qué sirven los Goals dentro de Hashcod Codespace?'),'Goals FAQ question 1 missing');
assert(js.includes('¿Cómo creo un Goal para mi proyecto?'),'Goals FAQ question 2 missing');
assert(js.includes('¿Puedo tener varios Goals al mismo tiempo?'),'Goals FAQ question 3 missing');
assert(js.includes('Los Goals representan los objetivos que deseas alcanzar con tu proyecto dentro de Hashcod Codespace.'),'Goals FAQ answer 1 missing');
assert(js.includes('Para crear un Goal, debes definir de forma clara qué deseas conseguir con tu proyecto.'),'Goals FAQ answer 2 missing');
assert(js.includes('Sí. Dentro de Hashcod Codespace puedes trabajar con varios Goals al mismo tiempo siempre que cada uno represente un objetivo claro dentro de tu proyecto.'),'Goals FAQ answer 3 missing');
assert(js.includes('function renderFaqAccordion'),'FAQ accordion renderer missing');
assert(js.includes('function setFaqTab'),'FAQ tab interaction missing');
assert(js.includes("faqOpenIndex=0"),'FAQ first item must open by default');
assert(gate.includes('Comenzar mi Solicitud'),'FAQ CTA label missing');
assert(js.includes('https://wa.me/18294721257?text='),'FAQ CTA WhatsApp target missing');
assert(js.includes('Hola, deseo comenzar mi solicitud en Hashcod Codespace.'),'FAQ CTA WhatsApp message missing');
assert(js.includes("hashcod:faq-start-request"),'FAQ start-request event hook missing');
assert(gate.includes('id="d5NavListDemo"'),'NavListCard demo container missing');
assert(gate.includes('Credentials and verification'),'Credentials and verification NavListCard title missing');
assert(gate.includes('Support'),'Support NavListCard title missing');
assert(gate.includes('Documents')&&gate.includes('Budget')&&gate.includes('Reports'),'Credentials and verification NavListCard provisional items missing');
assert(gate.includes('Help Center')&&gate.includes('Docs')&&gate.includes('Contact Us'),'Support NavListCard provisional items missing');
assert(css.includes('max-width:360px'),'NavListCard demo max width must match Spectrum UI');
assert(css.includes('grid-template-columns:repeat(2,minmax(0,1fr))'),'NavListCard demo must use two columns');
assert(css.includes('gap:12px'),'NavListCard demo 12px grid gap missing');
assert(css.includes('border-radius:16px'),'NavListCard 16px radius missing');
assert(css.includes('height:32px'),'NavListCard row 32px height missing');
assert(css.includes('transform:translateX(2px) scale(1)'),'NavListCard hover x+2 motion missing');
assert(css.includes('scale(.98)'),'NavListCard tap scale missing');
assert(css.includes('left:calc(100% + 12px)'),'NavListCard must sit to the right of FAQ');
assert(js.includes('hashcod:nav-list-action'),'NavListCard interaction hook missing');
assert(gate.includes('id="d5NumberTickerDemo"'),'NumberTicker demo container missing');
assert(gate.includes('How much does a spot in the square cost?'),'NumberTicker demo title missing');
assert(gate.includes('Each digit rolls to its new value.'),'NumberTicker demo caption missing');
assert(gate.includes('id="d5TickerDecrease"'),'NumberTicker decrease control missing');
assert(gate.includes('id="d5TickerRandomize"'),'NumberTicker randomize control missing');
assert(gate.includes('id="d5TickerIncrease"'),'NumberTicker increase control missing');
assert(css.includes('width:360px'),'NumberTicker demo must retain 360px width');
assert(css.includes('padding:40px 0'),'NumberTicker demo py-10 spacing missing');
assert(css.includes('border-radius:16px'),'NumberTicker rounded-2xl radius missing');
assert(css.includes('padding:24px'),'NumberTicker p-6 card padding missing');
assert(css.includes('font-size:40px'),'NumberTicker 40px value size missing');
assert(css.includes('letter-spacing:-.03em'),'NumberTicker tracking missing');
assert(css.includes('width:36px')&&css.includes('height:36px'),'NumberTicker round controls must be 36px');
assert(css.includes('height:1.1em'),'NumberTicker digit height contract missing');
assert(css.includes('transition-duration:.9s'),'NumberTicker 0.9s roll duration missing');
assert(css.includes('@keyframes numberTickerBlur'),'NumberTicker blur animation missing');
assert(js.includes('var NUMBER_TICKER_STEP=1250'),'NumberTicker STEP must be 1250');
assert(js.includes("return 48250;")&&js.includes('var numberTickerValue=loadStoredNumberTickerValue()'),'NumberTicker must default to 48250 when no stored value exists');
assert(js.includes('Math.max(0,numberTickerValue-NUMBER_TICKER_STEP)'),'NumberTicker decrease logic missing');
assert(js.includes('Math.round(10000+Math.random()*990000)'),'NumberTicker randomize range missing');
assert(js.includes('numberTickerValue+NUMBER_TICKER_STEP'),'NumberTicker increase logic missing');
assert(js.includes("NUMBER_TICKER_STORAGE_KEY='hashcod:number-ticker:value:v1'"),'NumberTicker persistence key missing');
assert(js.includes('window.localStorage.getItem(NUMBER_TICKER_STORAGE_KEY)'),'NumberTicker stored value load missing');
assert(js.includes('window.localStorage.setItem(NUMBER_TICKER_STORAGE_KEY'),'NumberTicker stored value write missing');
assert(js.includes('persistNumberTickerValue(numberTickerValue)'),'NumberTicker must persist every value change');
assert(js.includes('IntersectionObserver'),'NumberTicker start-on-view behavior missing');
assert(gate.includes('id="d5ScratchCardDemo"'),'ScratchCard demo container missing');
assert(gate.includes('Coupon unlocked'),'ScratchCard unlocked label missing');
assert(gate.includes('20% off'),'ScratchCard prize missing');
assert(gate.includes('SPECTRUM20'),'ScratchCard coupon code missing');
assert(gate.includes('Drag across the card to scratch off the foil'),'ScratchCard hint missing');
assert(gate.includes('Scratch again'),'ScratchCard reset label missing');
assert(gate.includes('Scratch to reveal your coupon code. Press Enter to reveal.'),'ScratchCard accessibility label missing');
assert(css.includes('width:320px'),'ScratchCard demo must retain 320px max width');
assert(css.includes('padding:32px 0'),'ScratchCard demo py-8 spacing missing');
assert(css.includes('padding:40px 24px'),'ScratchCard content px-6 py-10 spacing missing');
assert(css.includes('border-radius:16px'),'ScratchCard rounded-2xl radius missing');
assert(css.includes('.scratch-foil.revealed'),'ScratchCard foil fade state missing');
assert(css.includes('.sr-only{'),'Spectrum sr-only utility missing');
assert(css.includes('clip:rect(0,0,0,0)'),'ScratchCard accessibility-only text must be visually hidden');
assert(css.includes('width:1064px'),'ScratchCard must mount to the right of NumberTicker on desktop');
assert(js.includes('var SCRATCH_REVEAL_THRESHOLD=.5'),'ScratchCard reveal threshold must be 50%');
assert(js.includes('var SCRATCH_BRUSH_SIZE=28'),'ScratchCard brush size must be 28px');
assert(js.includes('var SCRATCH_SAMPLE_STRIDE=32'),'ScratchCard progress sampling stride missing');
assert(js.includes('var SCRATCH_CHECK_EVERY_MOVES=10'),'ScratchCard progress cadence missing');
assert(js.includes('var SCRATCH_MAX_PARTICLES=120'),'ScratchCard particle cap missing');
assert(js.includes('var SCRATCH_PARTICLE_GRAVITY=.18'),'ScratchCard particle gravity missing');
assert(js.includes("ctx.globalCompositeOperation='destination-out'"),'ScratchCard erase compositing missing');
assert(js.includes('cleared/sampled>=SCRATCH_REVEAL_THRESHOLD'),'ScratchCard progress reveal logic missing');
assert(js.includes("event.key==='Enter'||event.key===' '"),'ScratchCard keyboard reveal missing');
assert(js.includes("var value='SPECTRUM20'"),'ScratchCard clipboard value missing');
assert(js.includes('navigator.clipboard.writeText(value)'),'ScratchCard clipboard integration missing');
assert(js.includes('window.setTimeout(resetScratchCopyState,2000)'),'ScratchCard copied state timeout missing');
assert(js.includes('function resetScratchCard()'),'ScratchCard reset function missing');
assert(gate.includes('id="d5TiltCardDemo"'),'TiltCard demo container missing');
assert(gate.includes('Current price to purchase a slot'),'TiltCard slot price title missing');
assert(gate.includes('Este es el precio que debes pagar para adquirir un cupo en la plataforma'),'TiltCard slot price description missing');
assert(gate.includes('hashcod_icon_exact.svg'),'TiltCard must use repository platform icon');
assert(gate.includes('alt="Hashcod Codespace platform icon"'),'TiltCard platform icon alt missing');
assert(gate.includes('data-tilt-depth="50"'),'TiltCard title depth 50 missing');
assert(gate.includes('data-tilt-depth="30"'),'TiltCard description depth 30 missing');
assert(gate.includes('data-tilt-depth="80"'),'TiltCard media depth 80 missing');
assert(gate.includes('data-tilt-depth="40"'),'TiltCard price depth 40 missing');
assert(gate.includes('data-tilt-depth="60"'),'TiltCard button depth 60 missing');
assert(gate.includes('id="d5TiltPrice"'),'TiltCard synchronized price target missing');
assert(gate.includes('$48,250'),'TiltCard fallback price must match NumberTicker fallback');
assert(js.includes("var tiltPrice=document.getElementById('d5TiltPrice')"),'TiltCard price binding missing');
assert(js.includes('function syncSlotPrice(value)'),'TiltCard price sync function missing');
assert(js.includes("tiltPrice.textContent=formatted"),'TiltCard price text synchronization missing');
assert(js.includes('syncSlotPrice(numberTickerValue)'),'TiltCard must load persisted NumberTicker price');
assert(js.includes('syncSlotPrice(value)'),'TiltCard must update whenever NumberTicker renders');
assert(gate.includes('id="d5TiltWhatsApp"'),'TiltCard WhatsApp purchase button missing');
assert(gate.includes('Comprar cupo por WhatsApp'),'TiltCard WhatsApp accessibility label missing');
assert(gate.includes('tilt-whatsapp-icon'),'TiltCard WhatsApp SVG icon missing');
assert(gate.includes('fill="#40c351"'),'TiltCard WhatsApp green brand path missing');
assert(css.includes('.tilt-whatsapp-button{'),'TiltCard WhatsApp styling missing');
assert(js.includes("var tiltWhatsApp=document.getElementById('d5TiltWhatsApp')"),'TiltCard WhatsApp binding missing');
assert(js.includes('https://wa.me/18294721257?text='),'TiltCard WhatsApp target missing');
assert(js.includes("var currentPrice='$'+numberTickerFormat(numberTickerValue)"),'TiltCard WhatsApp must use current slot price');
assert(js.includes('hashcod:slot-purchase-whatsapp'),'TiltCard WhatsApp event hook missing');
assert(gate.includes('Move the pointer across the card — layers lift at different depths'),'TiltCard demo hint missing');
assert(css.includes('max-width:384px'),'TiltCard max-w-sm contract missing');
assert(css.includes('padding:40px 0'),'TiltCard py-10 spacing missing');
assert(css.includes('padding:24px'),'TiltCard p-6 surface padding missing');
assert(css.includes('perspective:1000px'),'TiltCard perspective must be 1000px');
assert(css.includes('top:calc(100% + 12px)'),'TiltCard must sit exactly 12px below NavListCards on desktop');
assert(css.includes('position:absolute'),'TiltCard desktop anchoring missing');
assert(css.includes('height:208px'),'TiltCard media h-52 height missing');
assert(css.includes('border-radius:12px'),'TiltCard media rounded-xl radius missing');
assert(css.includes('transform-style:preserve-3d'),'TiltCard preserve-3d behavior missing');
assert(js.includes('var TILT_MAX=12'),'TiltCard max tilt must be 12 degrees');
assert(js.includes('var TILT_SCALE=1.02'),'TiltCard hover scale must be 1.02');
assert(js.includes('var TILT_PRESS_SCALE=.99'),'TiltCard press scale must be .99');
assert(js.includes("stiffness:260,damping:22,mass:.6"),'TiltCard tracking spring contract missing');
assert(js.includes("stiffness:140,damping:18,mass:1"),'TiltCard reset spring contract missing');
assert(js.includes("event.pointerType!=='mouse'"),'TiltCard must engage only for mouse pointers');
assert(js.includes("rgba(255,255,255,.35)"),'TiltCard glare color missing');
assert(js.includes('applyTiltItems(true)'),'TiltCard item depth lift missing');
assert(js.includes('tiltReducedMotion()'),'TiltCard reduced-motion handling missing');
assert(js.includes("column.style.transform='translateY(-'+(target*1.1)+'em)'"),'NumberTicker per-digit rolling transform missing');
assert(gate.includes('id="d5DocumentsModal"'),'official documents modal missing');
assert(gate.includes('data-doc-id="onapi"'),'ONAPI document selector missing');
assert(gate.includes('data-doc-id="mercantil"'),'Mercantile Registry selector missing');
assert(gate.includes('data-doc-id="rnc"'),'RNC document selector missing');
assert(js.includes("if(label==='Documents')"),'Documents item must open viewer');
assert(js.includes('function openDocumentsModal'),'documents modal open function missing');
assert(js.includes('function closeDocumentsModal'),'documents modal close function missing');
assert(js.includes('function renderOfficialDocument'),'document renderer missing');
assert(js.includes("registration','336973'") || js.includes("['Núm. de registro','336973']"),'ONAPI registration 336973 missing');
assert(js.includes("['Registro Mercantil','3323LV-PF']"),'Mercantile Registry number missing');
assert(js.includes("['RNC','402-0936929-3']"),'RNC number missing');
assert(js.includes('696254deb3f1783f788d475c8b13b615ceb32440ce2b921ca946a030292464db'),'ONAPI evidence hash missing');
assert(js.includes('ec1077ab5fd6d81685f0976ab3451ef7f4fa5be230e8ffe94761365708ab3e31'),'Mercantile evidence hash missing');
assert(js.includes('72cd3363c15d503adcee3bf97158a0ff437b7228a532e9222256cbca515c3fbd'),'RNC evidence hash missing');
assert(css.includes('.documents-modal{'),'documents modal styling missing');
assert(css.includes('grid-template-columns:220px minmax(0,1fr)'),'desktop documents viewer layout missing');
assert(css.includes('.official-document{'),'official document sheet styling missing');
assert(gate.includes('documents-header-icon'),'Spectrum documents header icon missing');
assert(css.includes('border-radius:22px'),'Spectrum modal radius missing');
assert(css.includes('animation:documentsZoomIn'),'Spectrum desktop modal zoom animation missing');
assert(css.includes('border-radius:999px'),'Spectrum pill navigation styling missing');
assert(css.includes('.official-document-head{'),'Spectrum summary card missing');
assert(css.includes('border-radius:18px'),'Spectrum document card radius missing');
assert(css.includes('.document-description::before'),'Spectrum document scope info treatment missing');
assert(css.includes('@keyframes documentsSlideUp'),'Spectrum mobile sheet animation missing');
assert(css.includes('border-radius:24px 24px 0 0'),'Spectrum mobile bottom-sheet radius missing');

console.log('✓ Hardened two-phase ML-DSA-87 access contract verified');
+numberTickerFormat(numberTickerValue)"),'TiltCard WhatsApp must use current slot price');
assert(js.includes("hashcod:slot-purchase-whatsapp"),'TiltCard slot purchase event hook missing');
assert(gate.includes('Move the pointer across the card — layers lift at different depths'),'TiltCard demo hint missing');
assert(css.includes('max-width:384px'),'TiltCard max-w-sm contract missing');
assert(css.includes('padding:40px 0'),'TiltCard py-10 spacing missing');
assert(css.includes('padding:24px'),'TiltCard p-6 surface padding missing');
assert(css.includes('perspective:1000px'),'TiltCard perspective must be 1000px');
assert(css.includes('top:calc(100% + 12px)'),'TiltCard must sit exactly 12px below NavListCards on desktop');
assert(css.includes('position:absolute'),'TiltCard desktop anchoring missing');
assert(css.includes('height:208px'),'TiltCard media h-52 height missing');
assert(css.includes('border-radius:12px'),'TiltCard media rounded-xl radius missing');
assert(css.includes('transform-style:preserve-3d'),'TiltCard preserve-3d behavior missing');
assert(js.includes('var TILT_MAX=12'),'TiltCard max tilt must be 12 degrees');
assert(js.includes('var TILT_SCALE=1.02'),'TiltCard hover scale must be 1.02');
assert(js.includes('var TILT_PRESS_SCALE=.99'),'TiltCard press scale must be .99');
assert(js.includes("stiffness:260,damping:22,mass:.6"),'TiltCard tracking spring contract missing');
assert(js.includes("stiffness:140,damping:18,mass:1"),'TiltCard reset spring contract missing');
assert(js.includes("event.pointerType!=='mouse'"),'TiltCard must engage only for mouse pointers');
assert(js.includes("rgba(255,255,255,.35)"),'TiltCard glare color missing');
assert(js.includes('applyTiltItems(true)'),'TiltCard item depth lift missing');
assert(js.includes('tiltReducedMotion()'),'TiltCard reduced-motion handling missing');
assert(js.includes("column.style.transform='translateY(-'+(target*1.1)+'em)'"),'NumberTicker per-digit rolling transform missing');
assert(gate.includes('id="d5DocumentsModal"'),'official documents modal missing');
assert(gate.includes('data-doc-id="onapi"'),'ONAPI document selector missing');
assert(gate.includes('data-doc-id="mercantil"'),'Mercantile Registry selector missing');
assert(gate.includes('data-doc-id="rnc"'),'RNC document selector missing');
assert(js.includes("if(label==='Documents')"),'Documents item must open viewer');
assert(js.includes('function openDocumentsModal'),'documents modal open function missing');
assert(js.includes('function closeDocumentsModal'),'documents modal close function missing');
assert(js.includes('function renderOfficialDocument'),'document renderer missing');
assert(js.includes("registration','336973'") || js.includes("['Núm. de registro','336973']"),'ONAPI registration 336973 missing');
assert(js.includes("['Registro Mercantil','3323LV-PF']"),'Mercantile Registry number missing');
assert(js.includes("['RNC','402-0936929-3']"),'RNC number missing');
assert(js.includes('696254deb3f1783f788d475c8b13b615ceb32440ce2b921ca946a030292464db'),'ONAPI evidence hash missing');
assert(js.includes('ec1077ab5fd6d81685f0976ab3451ef7f4fa5be230e8ffe94761365708ab3e31'),'Mercantile evidence hash missing');
assert(js.includes('72cd3363c15d503adcee3bf97158a0ff437b7228a532e9222256cbca515c3fbd'),'RNC evidence hash missing');
assert(css.includes('.documents-modal{'),'documents modal styling missing');
assert(css.includes('grid-template-columns:220px minmax(0,1fr)'),'desktop documents viewer layout missing');
assert(css.includes('.official-document{'),'official document sheet styling missing');
assert(gate.includes('documents-header-icon'),'Spectrum documents header icon missing');
assert(css.includes('border-radius:22px'),'Spectrum modal radius missing');
assert(css.includes('animation:documentsZoomIn'),'Spectrum desktop modal zoom animation missing');
assert(css.includes('border-radius:999px'),'Spectrum pill navigation styling missing');
assert(css.includes('.official-document-head{'),'Spectrum summary card missing');
assert(css.includes('border-radius:18px'),'Spectrum document card radius missing');
assert(css.includes('.document-description::before'),'Spectrum document scope info treatment missing');
assert(css.includes('@keyframes documentsSlideUp'),'Spectrum mobile sheet animation missing');
assert(css.includes('border-radius:24px 24px 0 0'),'Spectrum mobile bottom-sheet radius missing');

console.log('✓ Hardened two-phase ML-DSA-87 access contract verified');
