'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '../..');
const registration = fs.readFileSync(path.join(root,'components/platform-registration-form.js'),'utf8');
const bridge = fs.readFileSync(path.join(root,'components/entry-registration-force.js'),'utf8');
const local = fs.readFileSync(path.join(root,'laragon-local-entry.php'),'utf8');
assert(registration.includes('registrationRetired: true'),'legacy registration must remain retired');
assert(registration.includes('registrationRestored: false'),'retired form must not claim active registration');
assert(registration.includes('cleanupRegistrationDom()'),'stale registration DOM must be removed');
assert(bridge.includes("mode: 'passive-no-form'"),'entry bridge must remain passive');
assert(!bridge.includes('installButtonGate'),'retired bridge must not intercept entry');
assert(local.includes('echo l8_apply_csp_nonce(mldsaGateHtml(hashcodLaragonBasePath(), true));'),'local must render the single current presentation');
console.log('PASS: retired registration stays passive and local entry uses the current nonced presentation');
