const fs=require('fs'),assert=require('assert');
const gate=fs.readFileSync('mldsa-access.php','utf8');
const api=fs.readFileSync('mldsa-access-api.php','utf8');
const css=fs.readFileSync('components/mldsa-access-gate.css','utf8');
const js=fs.readFileSync('components/mldsa-access-gate.js','utf8');
const l8=fs.readFileSync('l8-html.php','utf8');
const router=fs.readFileSync('router.php','utf8');
const req=fs.readFileSync('requirements-streamlit.txt','utf8');
const spotlightAsset=fs.readFileSync('components/mldsa-card-assets/spotlight-code.svg','utf8');
const pitAsset=fs.readFileSync('components/mldsa-card-assets/pit-barriers.svg','utf8');
const singleBedAsset=fs.readFileSync('components/mldsa-card-assets/single-bed-base.svg','utf8');
const tokenizedAsset=fs.readFileSync('components/mldsa-card-assets/tokenized-certification.svg','utf8');
const pubRaw=fs.readFileSync('config/mldsa87-access-public.b64','utf8');
const pub=pubRaw.replace(/\s+/g,'');
function crc32(str){let table=crc32.t;if(!table){table=crc32.t=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?(0xedb88320^(c>>>1)):(c>>>1);return c>>>0;});}let crc=0xffffffff;for(let i=0;i<str.length;i++)crc=table[(crc^str.charCodeAt(i))&255]^(crc>>>8);return (crc^0xffffffff)>>>0;}

assert.strictEqual(pub.length,3456,'ML-DSA-87 public key Base64 length must be exact');
assert(/^[A-Za-z0-9+/]+$/.test(pub),'ML-DSA-87 public key contains invalid Base64 characters');
assert.strictEqual(crc32(pub).toString(16).padStart(8,'0'),'25eb08f5','production ML-DSA-87 public key checksum mismatch');
assert.strictEqual(Buffer.from(pub,'base64').length,2592,'ML-DSA-87 public key must decode to 2592 bytes');

assert(gate.includes("strlen($sig)!==4627"),'signature length guard missing');
assert(gate.includes("HC-MLDSA87-V2.P1."),'phase-1 challenge prefix missing');
assert(gate.includes("HC-MLDSA87-V2.P2."),'phase-2 challenge prefix missing');
assert(gate.includes("function mldsaConsumeJti"),'atomic anti-replay JTI consumption missing');
assert(gate.includes("fopen($path,'x')"),'anti-replay store must use exclusive create');
assert(gate.includes("function mldsaOriginAllowed"),'same-origin request binding missing');
assert(gate.includes("phase1_proof"),'phase-2 challenge must bind phase-1 proof');
assert(gate.includes("parent_jti"),'phase-2 challenge must bind parent challenge');
assert(gate.includes("L8_ACCESS_MLDSA87_PHASE1_TTL"),'phase-1 TTL configuration missing');
assert(gate.includes("L8_ACCESS_MLDSA87_PHASE2_TTL"),'phase-2 TTL configuration missing');
assert(gate.includes("min(7200"),'access session maximum TTL cap missing');
assert(gate.includes("httponly'=>true"),'HttpOnly cookie missing');
assert(gate.includes("samesite'=>'Strict"),'SameSite Strict missing');
assert(gate.includes("function mldsaAccessRequired(): bool"),'required gate function missing');
assert(!gate.includes("if (!mldsaAccessConfigured()) return false;"),'gate must fail closed');

assert(api.includes("protocol'=>'ML-DSA-87-2PHASE"),'two-phase protocol marker missing');
assert(api.includes("replay_detected"),'replay rejection missing');
assert(api.includes("origin_mismatch"),'origin mismatch rejection missing');
assert(api.includes("phase_mismatch"),'phase mismatch rejection missing');
assert(api.includes("mldsaConsumeJti"),'API must consume one-time JTI');
assert(api.includes("securityIpStrike('mldsa_access_fail',3"),'progressive failure strike threshold missing');
assert(api.includes("securityIpIsBanned"),'IP temporary ban check missing');

assert(js.includes("Paso 1 de 2"),'phase-1 UI missing');
assert(js.includes("Paso 2 de 2"),'phase-2 UI missing');
assert(js.includes("next_phase"),'frontend phase transition missing');
assert(js.includes("phase:phase"),'frontend must bind submitted signature to current phase');
assert(css.includes(".security-progress{"),'two-phase progress UI missing');

assert(l8.includes('mldsaShouldGateHtml'),'HTML gate missing');
assert(router.includes("'/api/mldsa-access'"),'access route missing');
assert(req.includes('pqcrypto==1.0.0'),'pqcrypto pin missing');
assert(css.includes('max-width:380px'),'SpectrumUI compact card missing');
assert(css.includes('border-radius:24px'),'SpectrumUI card radius missing');
assert(gate.includes('id="d5ToolDeck"'),'animated tool deck missing');
assert(gate.includes('Spotlight Code'),'Spotlight Code card missing');
assert(gate.includes('Code focused on your custom enhancements, providing you with the necessary credentials to make fixes or changes.'),'Spotlight Code description missing');
assert(gate.includes('Pit Barriers'),'Pit Barriers card missing');
assert(gate.includes('Single bed base'),'Single bed base card missing');
assert(gate.includes('Tokenized certification'),'Tokenized certification card missing');
assert(gate.includes('Obtain your tokenized platform certification by integrating with our Codespace and contacting us.'),'Tokenized certification description missing');
assert(gate.includes('Rent out your unit through the CRM, and you can even sell or rent it to someone else.'),'Single bed base description missing');
assert(gate.includes('Barriers with intentional holes designed to lure your code into false traps.'),'Pit Barriers description missing');
assert(gate.includes('components/mldsa-card-assets/pit-barriers.svg'),'Pit Barriers asset missing from gate');
assert(gate.includes('components/mldsa-card-assets/single-bed-base.svg'),'Single bed base asset missing from gate');
assert(gate.includes('components/mldsa-card-assets/tokenized-certification.svg'),'Tokenized certification asset missing from gate');
assert(spotlightAsset.includes('M90,23.333L60,10'),'requested Spotlight Code SVG path missing');
assert(pitAsset.includes('M70,10H10v80h41.849'),'requested Pit Barriers SVG path missing');
assert(singleBedAsset.includes('M 50 10 C 33.431 10 20 15.969031'),'requested Single bed base SVG path missing');
assert(tokenizedAsset.includes('M 10 4 L 10 6 L 12 6'),'requested Tokenized certification SVG path missing');
assert(css.includes('width:320px'),'AnimatedCard must retain Spectrum UI 320px width');
assert(css.includes('width:128px')&&css.includes('height:128px'),'AnimatedCard logo must retain 128x128 size');
assert(css.includes('--x:-300px;--y:-65px;--rot:-20deg'),'card 1 expansion coordinates changed');
assert(css.includes('--x:-85px;--y:-120px;--rot:-10deg'),'card 2 expansion coordinates changed');
assert(css.includes('--x:150px;--y:-135px;--rot:5deg'),'card 3 expansion coordinates changed');
assert(css.includes('--x:340px;--y:-94px;--rot:17deg'),'card 4 expansion coordinates changed');
assert(js.includes('function setDeckExpanded'),'tool deck toggle logic missing');
assert(js.includes("deck.addEventListener('click'"),'tool deck click interaction missing');
assert(js.includes("deck.addEventListener('keydown'"),'tool deck keyboard interaction missing');

console.log('✓ Hardened two-phase ML-DSA-87 access contract verified');
