packages:
  - 'packages/*'
  - 'apps/*'
allowBuilds:
  '@prisma/engines': true
  prisma: true
  esbuild: true
  msgpackr-extract: false
verifyDepsBeforeRun: false

overrides:
  deepmerge-ts: 8.0.2
  mysql2: 3.24.5
