// Code generated by protoc-gen-go-grpc / pure Go gRPC engine for Hashcod Codespace.
// Source: proto/codespace_pqc.proto
// Package: pb

package pb

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"sync"
)

// ============================================================================
// gRPC Server & Client Interfaces
// ============================================================================

// SecurityTelemetryServiceServer is the server API for SecurityTelemetryService.
type SecurityTelemetryServiceServer interface {
	StreamSecurityTelemetry(*TelemetrySubscription, SecurityTelemetryService_StreamSecurityTelemetryServer) error
	GetSecurityStatus(context.Context, *SecurityStatusRequest) (*SecurityStatusResponse, error)
	ReportSecurityEvent(context.Context, *SecurityEventRequest) (*SecurityEventResponse, error)
}

// SecurityTelemetryService_StreamSecurityTelemetryServer is the streaming interface.
type SecurityTelemetryService_StreamSecurityTelemetryServer interface {
	Send(*SecurityTelemetryChunk) error
	Context() context.Context
}

// DilithiumServiceServer is the server API for DilithiumService.
type DilithiumServiceServer interface {
	VerifySignature(context.Context, *VerifyRequest) (*VerifyResponse, error)
	RegisterActiveKey(context.Context, *RegisterKeyRequest) (*RegisterKeyResponse, error)
	GetActiveKeyStatus(context.Context, *KeyStatusRequest) (*KeyStatusResponse, error)
	DeriveKeySeed(context.Context, *SeedRequest) (*SeedResponse, error)
}

// ============================================================================
// Pure Go High-Performance gRPC Server Engine
// ============================================================================

// GrpcServer hosts gRPC and gRPC-Web endpoints over HTTP/1.1 and HTTP/2.
type GrpcServer struct {
	mu               sync.RWMutex
	telemetryService SecurityTelemetryServiceServer
	dilithiumService DilithiumServiceServer
}

// NewGrpcServer creates a new high-performance gRPC server.
func NewGrpcServer() *GrpcServer {
	return &GrpcServer{}
}

// RegisterSecurityTelemetryServiceServer registers the telemetry server.
func (s *GrpcServer) RegisterSecurityTelemetryServiceServer(srv SecurityTelemetryServiceServer) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.telemetryService = srv
}

// RegisterDilithiumServiceServer registers the Dilithium verification server.
func (s *GrpcServer) RegisterDilithiumServiceServer(srv DilithiumServiceServer) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.dilithiumService = srv
}

func corsOriginAllowed(origin string) bool {
	origin = strings.TrimSpace(origin)
	if origin == "" {
		return true
	}
	u, err := url.Parse(origin)
	if err != nil {
		return false
	}
	host := strings.ToLower(u.Hostname())
	return host == "localhost" || host == "127.0.0.1" || host == "::1"
}

// SetCorsHeaders injects CORS headers only for explicit loopback browser origins.
func SetCorsHeaders(w http.ResponseWriter, r *http.Request) {
	origin := strings.TrimSpace(r.Header.Get("Origin"))
	if origin != "" && corsOriginAllowed(origin) {
		w.Header().Set("Access-Control-Allow-Origin", origin)
		w.Header().Set("Vary", "Origin")
	}
	w.Header().Set("Access-Control-Allow-Methods", "POST, GET, OPTIONS")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type, X-User-Agent, X-Grpc-Web, Authorization, X-Accept-Content-Transfer-Encoding, X-Accept-Response-Streaming")
	w.Header().Set("Access-Control-Expose-Headers", "grpc-status, grpc-message, grpc-status-details-bin")
}

// ServeHTTP handles gRPC and gRPC-Web RPC dispatches.
func (s *GrpcServer) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	SetCorsHeaders(w, r)

	if r.Method == http.MethodOptions {
		origin := strings.TrimSpace(r.Header.Get("Origin"))
		if origin != "" && !corsOriginAllowed(origin) {
			http.Error(w, "origin not allowed", http.StatusForbidden)
			return
		}
		w.WriteHeader(http.StatusNoContent)
		return
	}

	path := strings.TrimPrefix(r.URL.Path, "/")

	// Health check endpoint
	if path == "health" || path == "healthz" || path == "api/health" {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte(`{"status":"SERVING","service":"hashcod-codespace-grpc-daemon","version":"3.2.0-pqc-m1"}`))
		return
	}

	// Determine if this is a gRPC-Web request
	isGrpcWeb := strings.Contains(r.Header.Get("Content-Type"), "application/grpc-web") || r.Header.Get("X-Grpc-Web") == "1"
	isJson := strings.Contains(r.Header.Get("Content-Type"), "application/json")

	// Read body payload
	bodyBytes, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, fmt.Sprintf("failed to read body: %v", err), http.StatusBadRequest)
		return
	}

	// Strip 5-byte gRPC frame header if present: [1B flag][4B big-endian length]
	var payload []byte
	if len(bodyBytes) >= 5 && (bodyBytes[0] == 0x00 || bodyBytes[0] == 0x80) && !isJson {
		frameLen := binary.BigEndian.Uint32(bodyBytes[1:5])
		if int(frameLen) <= len(bodyBytes)-5 {
			payload = bodyBytes[5 : 5+frameLen]
		} else {
			payload = bodyBytes[5:]
		}
	} else {
		payload = bodyBytes
	}

	ctx := r.Context()

	switch path {
	// ------------------------------------------------------------------------
	// SecurityTelemetryService Endpoints
	// ------------------------------------------------------------------------
	case "hashcod.pqc.v1.SecurityTelemetryService/StreamSecurityTelemetry",
		"SecurityTelemetryService/StreamSecurityTelemetry":
		s.handleStreamTelemetry(w, r, ctx, payload, isGrpcWeb, isJson)

	case "hashcod.pqc.v1.SecurityTelemetryService/GetSecurityStatus",
		"SecurityTelemetryService/GetSecurityStatus":
		s.handleGetSecurityStatus(w, ctx, payload, isGrpcWeb, isJson)

	case "hashcod.pqc.v1.SecurityTelemetryService/ReportSecurityEvent",
		"SecurityTelemetryService/ReportSecurityEvent":
		s.handleReportSecurityEvent(w, ctx, payload, isGrpcWeb, isJson)

	// ------------------------------------------------------------------------
	// DilithiumService Endpoints
	// ------------------------------------------------------------------------
	case "hashcod.pqc.v1.DilithiumService/VerifySignature",
		"DilithiumService/VerifySignature":
		s.handleVerifySignature(w, ctx, payload, isGrpcWeb, isJson)

	case "hashcod.pqc.v1.DilithiumService/RegisterActiveKey",
		"DilithiumService/RegisterActiveKey":
		s.handleRegisterActiveKey(w, ctx, payload, isGrpcWeb, isJson)

	case "hashcod.pqc.v1.DilithiumService/GetActiveKeyStatus",
		"DilithiumService/GetActiveKeyStatus":
		s.handleGetActiveKeyStatus(w, ctx, payload, isGrpcWeb, isJson)

	case "hashcod.pqc.v1.DilithiumService/DeriveKeySeed",
		"DilithiumService/DeriveKeySeed":
		s.handleDeriveKeySeed(w, ctx, payload, isGrpcWeb, isJson)

	default:
		w.Header().Set("grpc-status", "12") // UNIMPLEMENTED
		w.Header().Set("grpc-message", fmt.Sprintf("unknown method: %s", path))
		w.WriteHeader(http.StatusNotFound)
		_, _ = w.Write([]byte(fmt.Sprintf(`{"error":"unknown method: %s"}`, path)))
	}
}

// ----------------------------------------------------------------------------
// gRPC Response Helpers
// ----------------------------------------------------------------------------

func writeGrpcUnaryResponse(w http.ResponseWriter, respBytes []byte, isGrpcWeb bool, isJson bool) {
	if isJson {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write(respBytes)
		return
	}

	contentType := "application/grpc"
	if isGrpcWeb {
		contentType = "application/grpc-web+proto"
	}
	w.Header().Set("Content-Type", contentType)
	w.Header().Set("grpc-status", "0")
	w.Header().Set("grpc-message", "OK")

	// 5-byte gRPC data frame header: [0x00][4B big-endian length]
	var frameHeader [5]byte
	frameHeader[0] = 0x00
	binary.BigEndian.PutUint32(frameHeader[1:], uint32(len(respBytes)))

	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(frameHeader[:])
	_, _ = w.Write(respBytes)

	// If gRPC-Web, emit trailers frame (flag 0x80)
	if isGrpcWeb {
		trailer := []byte("grpc-status: 0\r\ngrpc-message: OK\r\n")
		var trailerHeader [5]byte
		trailerHeader[0] = 0x80
		binary.BigEndian.PutUint32(trailerHeader[1:], uint32(len(trailer)))
		_, _ = w.Write(trailerHeader[:])
		_, _ = w.Write(trailer)
	}
}

func writeGrpcError(w http.ResponseWriter, code int, msg string, isGrpcWeb bool, isJson bool) {
	if isJson {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		_ = json.NewEncoder(w).Encode(map[string]interface{}{
			"error":   msg,
			"code":    code,
			"grpc_status": code,
		})
		return
	}

	contentType := "application/grpc"
	if isGrpcWeb {
		contentType = "application/grpc-web+proto"
	}
	w.Header().Set("Content-Type", contentType)
	w.Header().Set("grpc-status", fmt.Sprintf("%d", code))
	w.Header().Set("grpc-message", msg)
	w.WriteHeader(http.StatusOK)

	if isGrpcWeb {
		trailer := []byte(fmt.Sprintf("grpc-status: %d\r\ngrpc-message: %s\r\n", code, msg))
		var trailerHeader [5]byte
		trailerHeader[0] = 0x80
		binary.BigEndian.PutUint32(trailerHeader[1:], uint32(len(trailer)))
		_, _ = w.Write(trailerHeader[:])
		_, _ = w.Write(trailer)
	}
}

// ----------------------------------------------------------------------------
// Handlers for SecurityTelemetryService
// ----------------------------------------------------------------------------

type httpTelemetryStreamServer struct {
	w         http.ResponseWriter
	flusher   http.Flusher
	ctx       context.Context
	isGrpcWeb bool
	isJson    bool
	mu        sync.Mutex
}

func (s *httpTelemetryStreamServer) Context() context.Context {
	return s.ctx
}

func (s *httpTelemetryStreamServer) Send(chunk *SecurityTelemetryChunk) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	var chunkBytes []byte
	var err error
	if s.isJson {
		chunkBytes, err = json.Marshal(chunk)
		if err != nil {
			return err
		}
		chunkBytes = append(chunkBytes, '\n')
		_, err = s.w.Write(chunkBytes)
	} else {
		chunkBytes, err = chunk.Marshal()
		if err != nil {
			return err
		}
		var frameHeader [5]byte
		frameHeader[0] = 0x00
		binary.BigEndian.PutUint32(frameHeader[1:], uint32(len(chunkBytes)))
		if _, err = s.w.Write(frameHeader[:]); err != nil {
			return err
		}
		if _, err = s.w.Write(chunkBytes); err != nil {
			return err
		}
	}

	if s.flusher != nil {
		s.flusher.Flush()
	}
	return err
}

func (s *GrpcServer) handleStreamTelemetry(w http.ResponseWriter, r *http.Request, ctx context.Context, payload []byte, isGrpcWeb bool, isJson bool) {
	s.mu.RLock()
	srv := s.telemetryService
	s.mu.RUnlock()

	if srv == nil {
		writeGrpcError(w, 14, "SecurityTelemetryService not registered", isGrpcWeb, isJson)
		return
	}

	req := &TelemetrySubscription{}
	if len(payload) > 0 {
		if isJson {
			_ = json.Unmarshal(payload, req)
		} else {
			_ = req.Unmarshal(payload)
		}
	}

	contentType := "application/grpc"
	if isGrpcWeb {
		contentType = "application/grpc-web+proto"
	}
	if isJson {
		contentType = "application/x-ndjson"
	}

	w.Header().Set("Content-Type", contentType)
	w.Header().Set("Transfer-Encoding", "chunked")
	w.Header().Set("grpc-status", "0")
	w.Header().Set("grpc-message", "OK")
	w.WriteHeader(http.StatusOK)

	flusher, _ := w.(http.Flusher)
	if flusher != nil {
		flusher.Flush()
	}

	stream := &httpTelemetryStreamServer{
		w:         w,
		flusher:   flusher,
		ctx:       ctx,
		isGrpcWeb: isGrpcWeb,
		isJson:    isJson,
	}

	err := srv.StreamSecurityTelemetry(req, stream)
	if isGrpcWeb {
		var trailer []byte
		if err != nil {
			trailer = []byte(fmt.Sprintf("grpc-status: 13\r\ngrpc-message: %s\r\n", err.Error()))
		} else {
			trailer = []byte("grpc-status: 0\r\ngrpc-message: OK\r\n")
		}
		var trailerHeader [5]byte
		trailerHeader[0] = 0x80
		binary.BigEndian.PutUint32(trailerHeader[1:], uint32(len(trailer)))
		_, _ = w.Write(trailerHeader[:])
		_, _ = w.Write(trailer)
		if flusher != nil {
			flusher.Flush()
		}
	}
}

func (s *GrpcServer) handleGetSecurityStatus(w http.ResponseWriter, ctx context.Context, payload []byte, isGrpcWeb bool, isJson bool) {
	s.mu.RLock()
	srv := s.telemetryService
	s.mu.RUnlock()

	if srv == nil {
		writeGrpcError(w, 14, "SecurityTelemetryService not registered", isGrpcWeb, isJson)
		return
	}

	req := &SecurityStatusRequest{}
	if len(payload) > 0 {
		if isJson {
			_ = json.Unmarshal(payload, req)
		} else {
			_ = req.Unmarshal(payload)
		}
	}

	resp, err := srv.GetSecurityStatus(ctx, req)
	if err != nil {
		writeGrpcError(w, 13, err.Error(), isGrpcWeb, isJson)
		return
	}

	var respBytes []byte
	if isJson {
		respBytes, _ = json.Marshal(resp)
	} else {
		respBytes, _ = resp.Marshal()
	}
	writeGrpcUnaryResponse(w, respBytes, isGrpcWeb, isJson)
}

func (s *GrpcServer) handleReportSecurityEvent(w http.ResponseWriter, ctx context.Context, payload []byte, isGrpcWeb bool, isJson bool) {
	s.mu.RLock()
	srv := s.telemetryService
	s.mu.RUnlock()

	if srv == nil {
		writeGrpcError(w, 14, "SecurityTelemetryService not registered", isGrpcWeb, isJson)
		return
	}

	req := &SecurityEventRequest{}
	if len(payload) > 0 {
		if isJson {
			_ = json.Unmarshal(payload, req)
		} else {
			_ = req.Unmarshal(payload)
		}
	}

	resp, err := srv.ReportSecurityEvent(ctx, req)
	if err != nil {
		writeGrpcError(w, 13, err.Error(), isGrpcWeb, isJson)
		return
	}

	var respBytes []byte
	if isJson {
		respBytes, _ = json.Marshal(resp)
	} else {
		respBytes, _ = resp.Marshal()
	}
	writeGrpcUnaryResponse(w, respBytes, isGrpcWeb, isJson)
}

// ----------------------------------------------------------------------------
// Handlers for DilithiumService
// ----------------------------------------------------------------------------

func (s *GrpcServer) handleVerifySignature(w http.ResponseWriter, ctx context.Context, payload []byte, isGrpcWeb bool, isJson bool) {
	s.mu.RLock()
	srv := s.dilithiumService
	s.mu.RUnlock()

	if srv == nil {
		writeGrpcError(w, 14, "DilithiumService not registered", isGrpcWeb, isJson)
		return
	}

	req := &VerifyRequest{}
	if len(payload) > 0 {
		if isJson {
			_ = json.Unmarshal(payload, req)
		} else {
			_ = req.Unmarshal(payload)
		}
	}

	resp, err := srv.VerifySignature(ctx, req)
	if err != nil {
		writeGrpcError(w, 13, err.Error(), isGrpcWeb, isJson)
		return
	}

	var respBytes []byte
	if isJson {
		respBytes, _ = json.Marshal(resp)
	} else {
		respBytes, _ = resp.Marshal()
	}
	writeGrpcUnaryResponse(w, respBytes, isGrpcWeb, isJson)
}

func (s *GrpcServer) handleRegisterActiveKey(w http.ResponseWriter, ctx context.Context, payload []byte, isGrpcWeb bool, isJson bool) {
	s.mu.RLock()
	srv := s.dilithiumService
	s.mu.RUnlock()

	if srv == nil {
		writeGrpcError(w, 14, "DilithiumService not registered", isGrpcWeb, isJson)
		return
	}

	req := &RegisterKeyRequest{}
	if len(payload) > 0 {
		if isJson {
			_ = json.Unmarshal(payload, req)
		} else {
			_ = req.Unmarshal(payload)
		}
	}

	resp, err := srv.RegisterActiveKey(ctx, req)
	if err != nil {
		writeGrpcError(w, 13, err.Error(), isGrpcWeb, isJson)
		return
	}

	var respBytes []byte
	if isJson {
		respBytes, _ = json.Marshal(resp)
	} else {
		respBytes, _ = resp.Marshal()
	}
	writeGrpcUnaryResponse(w, respBytes, isGrpcWeb, isJson)
}

func (s *GrpcServer) handleGetActiveKeyStatus(w http.ResponseWriter, ctx context.Context, payload []byte, isGrpcWeb bool, isJson bool) {
	s.mu.RLock()
	srv := s.dilithiumService
	s.mu.RUnlock()

	if srv == nil {
		writeGrpcError(w, 14, "DilithiumService not registered", isGrpcWeb, isJson)
		return
	}

	req := &KeyStatusRequest{}
	if len(payload) > 0 {
		if isJson {
			_ = json.Unmarshal(payload, req)
		} else {
			_ = req.Unmarshal(payload)
		}
	}

	resp, err := srv.GetActiveKeyStatus(ctx, req)
	if err != nil {
		writeGrpcError(w, 13, err.Error(), isGrpcWeb, isJson)
		return
	}

	var respBytes []byte
	if isJson {
		respBytes, _ = json.Marshal(resp)
	} else {
		respBytes, _ = resp.Marshal()
	}
	writeGrpcUnaryResponse(w, respBytes, isGrpcWeb, isJson)
}

func (s *GrpcServer) handleDeriveKeySeed(w http.ResponseWriter, ctx context.Context, payload []byte, isGrpcWeb bool, isJson bool) {
	s.mu.RLock()
	srv := s.dilithiumService
	s.mu.RUnlock()

	if srv == nil {
		writeGrpcError(w, 14, "DilithiumService not registered", isGrpcWeb, isJson)
		return
	}

	req := &SeedRequest{}
	if len(payload) > 0 {
		if isJson {
			_ = json.Unmarshal(payload, req)
		} else {
			_ = req.Unmarshal(payload)
		}
	}

	resp, err := srv.DeriveKeySeed(ctx, req)
	if err != nil {
		writeGrpcError(w, 13, err.Error(), isGrpcWeb, isJson)
		return
	}

	var respBytes []byte
	if isJson {
		respBytes, _ = json.Marshal(resp)
	} else {
		respBytes, _ = resp.Marshal()
	}
	writeGrpcUnaryResponse(w, respBytes, isGrpcWeb, isJson)
}

// Ensure interface compatibility
var _ = bytes.NewReader
