// Code generated by protoc-gen-go / pure Go protobuf engine for Hashcod Codespace.
// Source: proto/codespace_pqc.proto
// Package: pb

package pb

import (
	"encoding/binary"
	"encoding/json"
	"fmt"
	"math"
)

// ============================================================================
// Protocol Buffers Wire Format Encoders / Decoders
// ============================================================================

func appendVarint(buf []byte, v uint64) []byte {
	for v >= 0x80 {
		buf = append(buf, byte(v)|0x80)
		v >>= 7
	}
	return append(buf, byte(v))
}

func appendTag(buf []byte, fieldNum int, wireType int) []byte {
	tag := uint64((fieldNum << 3) | (wireType & 0x07))
	return appendVarint(buf, tag)
}

func encodeVarintField(buf []byte, fieldNum int, val uint64) []byte {
	buf = appendTag(buf, fieldNum, 0)
	return appendVarint(buf, val)
}

func encodeFixed64Field(buf []byte, fieldNum int, val uint64) []byte {
	buf = appendTag(buf, fieldNum, 1)
	var b [8]byte
	binary.LittleEndian.PutUint64(b[:], val)
	return append(buf, b[:]...)
}

func encodeBytesField(buf []byte, fieldNum int, val []byte) []byte {
	buf = appendTag(buf, fieldNum, 2)
	buf = appendVarint(buf, uint64(len(val)))
	return append(buf, val...)
}

func encodeStringField(buf []byte, fieldNum int, val string) []byte {
	if len(val) == 0 {
		return buf
	}
	return encodeBytesField(buf, fieldNum, []byte(val))
}

func readVarint(data []byte, offset int) (uint64, int, error) {
	var val uint64
	var shift uint
	idx := offset
	for {
		if idx >= len(data) {
			return 0, idx, fmt.Errorf("unexpected EOF reading varint")
		}
		b := data[idx]
		idx++
		val |= uint64(b&0x7F) << shift
		if (b & 0x80) == 0 {
			break
		}
		shift += 7
		if shift >= 64 {
			return 0, idx, fmt.Errorf("varint overflow")
		}
	}
	return val, idx, nil
}

func readFixed64(data []byte, offset int) (uint64, int, error) {
	if offset+8 > len(data) {
		return 0, offset, fmt.Errorf("unexpected EOF reading fixed64")
	}
	val := binary.LittleEndian.Uint64(data[offset : offset+8])
	return val, offset + 8, nil
}

func readLengthDelimited(data []byte, offset int) ([]byte, int, error) {
	length, next, err := readVarint(data, offset)
	if err != nil {
		return nil, offset, err
	}
	end := next + int(length)
	if end > len(data) {
		return nil, offset, fmt.Errorf("unexpected EOF reading bytes (len %d, remain %d)", length, len(data)-next)
	}
	return data[next:end], end, nil
}

// ============================================================================
// Message Definitions
// ============================================================================

// TelemetrySubscription initiates a live streaming session.
type TelemetrySubscription struct {
	ClientId         string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	IncludeRawLogs   bool   `protobuf:"varint,2,opt,name=include_raw_logs,json=includeRawLogs,proto3" json:"include_raw_logs,omitempty"`
	HeartbeatSeconds int32  `protobuf:"varint,3,opt,name=heartbeat_seconds,json=heartbeatSeconds,proto3" json:"heartbeat_seconds,omitempty"`
}

func (m *TelemetrySubscription) Reset()         { *m = TelemetrySubscription{} }
func (m *TelemetrySubscription) String() string { b, _ := json.Marshal(m); return string(b) }
func (*TelemetrySubscription) ProtoMessage()    {}

func (m *TelemetrySubscription) Marshal() ([]byte, error) {
	var buf []byte
	if len(m.ClientId) > 0 {
		buf = encodeStringField(buf, 1, m.ClientId)
	}
	if m.IncludeRawLogs {
		buf = encodeVarintField(buf, 2, 1)
	}
	if m.HeartbeatSeconds != 0 {
		buf = encodeVarintField(buf, 3, uint64(m.HeartbeatSeconds))
	}
	return buf, nil
}

func (m *TelemetrySubscription) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.ClientId = string(bytesVal)
			offset = next
		case 2:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.IncludeRawLogs = val != 0
			offset = next
		case 3:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.HeartbeatSeconds = int32(val)
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// SecurityTelemetryChunk represents a single real-time telemetry frame.
type SecurityTelemetryChunk struct {
	HealthScore         int32   `protobuf:"varint,1,opt,name=health_score,json=healthScore,proto3" json:"health_score,omitempty"`
	CvesScanned         int32   `protobuf:"varint,2,opt,name=cves_scanned,json=cvesScanned,proto3" json:"cves_scanned,omitempty"`
	CvesDetected        int32   `protobuf:"varint,3,opt,name=cves_detected,json=cvesDetected,proto3" json:"cves_detected,omitempty"`
	ThreatsBlocked      int32   `protobuf:"varint,4,opt,name=threats_blocked,json=threatsBlocked,proto3" json:"threats_blocked,omitempty"`
	HoneypotHits        int32   `protobuf:"varint,5,opt,name=honeypot_hits,json=honeypotHits,proto3" json:"honeypot_hits,omitempty"`
	EntropyPoolBytes    int32   `protobuf:"varint,6,opt,name=entropy_pool_bytes,json=entropyPoolBytes,proto3" json:"entropy_pool_bytes,omitempty"`
	QuantumStatus       string  `protobuf:"bytes,7,opt,name=quantum_status,json=quantumStatus,proto3" json:"quantum_status,omitempty"`
	AtomicTimeStatus    string  `protobuf:"bytes,8,opt,name=atomic_time_status,json=atomicTimeStatus,proto3" json:"atomic_time_status,omitempty"`
	CircuitBreakerState string  `protobuf:"bytes,9,opt,name=circuit_breaker_state,json=circuitBreakerState,proto3" json:"circuit_breaker_state,omitempty"`
	LastEdgeTimestamp   float64 `protobuf:"fixed64,10,opt,name=last_edge_timestamp,json=lastEdgeTimestamp,proto3" json:"last_edge_timestamp,omitempty"`
	TimestampUnixMs     int64   `protobuf:"varint,11,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Message             string  `protobuf:"bytes,12,opt,name=message,proto3" json:"message,omitempty"`
	ActiveKeyHash       string  `protobuf:"bytes,13,opt,name=active_key_hash,json=activeKeyHash,proto3" json:"active_key_hash,omitempty"`
}

func (m *SecurityTelemetryChunk) Reset()         { *m = SecurityTelemetryChunk{} }
func (m *SecurityTelemetryChunk) String() string { b, _ := json.Marshal(m); return string(b) }
func (*SecurityTelemetryChunk) ProtoMessage()    {}

func (m *SecurityTelemetryChunk) Marshal() ([]byte, error) {
	var buf []byte
	if m.HealthScore != 0 {
		buf = encodeVarintField(buf, 1, uint64(m.HealthScore))
	}
	if m.CvesScanned != 0 {
		buf = encodeVarintField(buf, 2, uint64(m.CvesScanned))
	}
	if m.CvesDetected != 0 {
		buf = encodeVarintField(buf, 3, uint64(m.CvesDetected))
	}
	if m.ThreatsBlocked != 0 {
		buf = encodeVarintField(buf, 4, uint64(m.ThreatsBlocked))
	}
	if m.HoneypotHits != 0 {
		buf = encodeVarintField(buf, 5, uint64(m.HoneypotHits))
	}
	if m.EntropyPoolBytes != 0 {
		buf = encodeVarintField(buf, 6, uint64(m.EntropyPoolBytes))
	}
	if len(m.QuantumStatus) > 0 {
		buf = encodeStringField(buf, 7, m.QuantumStatus)
	}
	if len(m.AtomicTimeStatus) > 0 {
		buf = encodeStringField(buf, 8, m.AtomicTimeStatus)
	}
	if len(m.CircuitBreakerState) > 0 {
		buf = encodeStringField(buf, 9, m.CircuitBreakerState)
	}
	if m.LastEdgeTimestamp != 0 {
		buf = encodeFixed64Field(buf, 10, math.Float64bits(m.LastEdgeTimestamp))
	}
	if m.TimestampUnixMs != 0 {
		buf = encodeVarintField(buf, 11, uint64(m.TimestampUnixMs))
	}
	if len(m.Message) > 0 {
		buf = encodeStringField(buf, 12, m.Message)
	}
	if len(m.ActiveKeyHash) > 0 {
		buf = encodeStringField(buf, 13, m.ActiveKeyHash)
	}
	return buf, nil
}

func (m *SecurityTelemetryChunk) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.HealthScore = int32(val)
			offset = next
		case 2:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.CvesScanned = int32(val)
			offset = next
		case 3:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.CvesDetected = int32(val)
			offset = next
		case 4:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.ThreatsBlocked = int32(val)
			offset = next
		case 5:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.HoneypotHits = int32(val)
			offset = next
		case 6:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.EntropyPoolBytes = int32(val)
			offset = next
		case 7:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.QuantumStatus = string(bytesVal)
			offset = next
		case 8:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.AtomicTimeStatus = string(bytesVal)
			offset = next
		case 9:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.CircuitBreakerState = string(bytesVal)
			offset = next
		case 10:
			bits, next, err := readFixed64(data, offset)
			if err != nil {
				return err
			}
			m.LastEdgeTimestamp = math.Float64frombits(bits)
			offset = next
		case 11:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.TimestampUnixMs = int64(val)
			offset = next
		case 12:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.Message = string(bytesVal)
			offset = next
		case 13:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.ActiveKeyHash = string(bytesVal)
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// SecurityStatusRequest requests an instantaneous snapshot of platform security metrics.
type SecurityStatusRequest struct {
	RequesterId string `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
}

func (m *SecurityStatusRequest) Reset()         { *m = SecurityStatusRequest{} }
func (m *SecurityStatusRequest) String() string { b, _ := json.Marshal(m); return string(b) }
func (*SecurityStatusRequest) ProtoMessage()    {}

func (m *SecurityStatusRequest) Marshal() ([]byte, error) {
	var buf []byte
	if len(m.RequesterId) > 0 {
		buf = encodeStringField(buf, 1, m.RequesterId)
	}
	return buf, nil
}

func (m *SecurityStatusRequest) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.RequesterId = string(bytesVal)
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// SecurityStatusResponse contains a snapshot of platform security metrics.
type SecurityStatusResponse struct {
	HealthScore         int32   `protobuf:"varint,1,opt,name=health_score,json=healthScore,proto3" json:"health_score,omitempty"`
	CvesScanned         int32   `protobuf:"varint,2,opt,name=cves_scanned,json=cvesScanned,proto3" json:"cves_scanned,omitempty"`
	CvesDetected        int32   `protobuf:"varint,3,opt,name=cves_detected,json=cvesDetected,proto3" json:"cves_detected,omitempty"`
	ThreatsBlocked      int32   `protobuf:"varint,4,opt,name=threats_blocked,json=threatsBlocked,proto3" json:"threats_blocked,omitempty"`
	HoneypotHits        int32   `protobuf:"varint,5,opt,name=honeypot_hits,json=honeypotHits,proto3" json:"honeypot_hits,omitempty"`
	EntropyPoolBytes    int32   `protobuf:"varint,6,opt,name=entropy_pool_bytes,json=entropyPoolBytes,proto3" json:"entropy_pool_bytes,omitempty"`
	QuantumStatus       string  `protobuf:"bytes,7,opt,name=quantum_status,json=quantumStatus,proto3" json:"quantum_status,omitempty"`
	AtomicTimeStatus    string  `protobuf:"bytes,8,opt,name=atomic_time_status,json=atomicTimeStatus,proto3" json:"atomic_time_status,omitempty"`
	CircuitBreakerState string  `protobuf:"bytes,9,opt,name=circuit_breaker_state,json=circuitBreakerState,proto3" json:"circuit_breaker_state,omitempty"`
	LastEdgeTimestamp   float64 `protobuf:"fixed64,10,opt,name=last_edge_timestamp,json=lastEdgeTimestamp,proto3" json:"last_edge_timestamp,omitempty"`
	ActiveKeyHash       string  `protobuf:"bytes,11,opt,name=active_key_hash,json=activeKeyHash,proto3" json:"active_key_hash,omitempty"`
	TimestampUnixMs     int64   `protobuf:"varint,12,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	DaemonVersion       string  `protobuf:"bytes,13,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
}

func (m *SecurityStatusResponse) Reset()         { *m = SecurityStatusResponse{} }
func (m *SecurityStatusResponse) String() string { b, _ := json.Marshal(m); return string(b) }
func (*SecurityStatusResponse) ProtoMessage()    {}

func (m *SecurityStatusResponse) Marshal() ([]byte, error) {
	var buf []byte
	if m.HealthScore != 0 {
		buf = encodeVarintField(buf, 1, uint64(m.HealthScore))
	}
	if m.CvesScanned != 0 {
		buf = encodeVarintField(buf, 2, uint64(m.CvesScanned))
	}
	if m.CvesDetected != 0 {
		buf = encodeVarintField(buf, 3, uint64(m.CvesDetected))
	}
	if m.ThreatsBlocked != 0 {
		buf = encodeVarintField(buf, 4, uint64(m.ThreatsBlocked))
	}
	if m.HoneypotHits != 0 {
		buf = encodeVarintField(buf, 5, uint64(m.HoneypotHits))
	}
	if m.EntropyPoolBytes != 0 {
		buf = encodeVarintField(buf, 6, uint64(m.EntropyPoolBytes))
	}
	if len(m.QuantumStatus) > 0 {
		buf = encodeStringField(buf, 7, m.QuantumStatus)
	}
	if len(m.AtomicTimeStatus) > 0 {
		buf = encodeStringField(buf, 8, m.AtomicTimeStatus)
	}
	if len(m.CircuitBreakerState) > 0 {
		buf = encodeStringField(buf, 9, m.CircuitBreakerState)
	}
	if m.LastEdgeTimestamp != 0 {
		buf = encodeFixed64Field(buf, 10, math.Float64bits(m.LastEdgeTimestamp))
	}
	if len(m.ActiveKeyHash) > 0 {
		buf = encodeStringField(buf, 11, m.ActiveKeyHash)
	}
	if m.TimestampUnixMs != 0 {
		buf = encodeVarintField(buf, 12, uint64(m.TimestampUnixMs))
	}
	if len(m.DaemonVersion) > 0 {
		buf = encodeStringField(buf, 13, m.DaemonVersion)
	}
	return buf, nil
}

func (m *SecurityStatusResponse) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.HealthScore = int32(val)
			offset = next
		case 2:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.CvesScanned = int32(val)
			offset = next
		case 3:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.CvesDetected = int32(val)
			offset = next
		case 4:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.ThreatsBlocked = int32(val)
			offset = next
		case 5:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.HoneypotHits = int32(val)
			offset = next
		case 6:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.EntropyPoolBytes = int32(val)
			offset = next
		case 7:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.QuantumStatus = string(bytesVal)
			offset = next
		case 8:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.AtomicTimeStatus = string(bytesVal)
			offset = next
		case 9:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.CircuitBreakerState = string(bytesVal)
			offset = next
		case 10:
			bits, next, err := readFixed64(data, offset)
			if err != nil {
				return err
			}
			m.LastEdgeTimestamp = math.Float64frombits(bits)
			offset = next
		case 11:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.ActiveKeyHash = string(bytesVal)
			offset = next
		case 12:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.TimestampUnixMs = int64(val)
			offset = next
		case 13:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.DaemonVersion = string(bytesVal)
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// SecurityEventRequest records a blocked threat or security anomaly.
type SecurityEventRequest struct {
	EventType   string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SourceIp    string `protobuf:"bytes,2,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	Severity    string `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
}

func (m *SecurityEventRequest) Reset()         { *m = SecurityEventRequest{} }
func (m *SecurityEventRequest) String() string { b, _ := json.Marshal(m); return string(b) }
func (*SecurityEventRequest) ProtoMessage()    {}

func (m *SecurityEventRequest) Marshal() ([]byte, error) {
	var buf []byte
	if len(m.EventType) > 0 {
		buf = encodeStringField(buf, 1, m.EventType)
	}
	if len(m.SourceIp) > 0 {
		buf = encodeStringField(buf, 2, m.SourceIp)
	}
	if len(m.Severity) > 0 {
		buf = encodeStringField(buf, 3, m.Severity)
	}
	if len(m.Description) > 0 {
		buf = encodeStringField(buf, 4, m.Description)
	}
	return buf, nil
}

func (m *SecurityEventRequest) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.EventType = string(bytesVal)
			offset = next
		case 2:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.SourceIp = string(bytesVal)
			offset = next
		case 3:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.Severity = string(bytesVal)
			offset = next
		case 4:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.Description = string(bytesVal)
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// SecurityEventResponse confirms registration of the security event.
type SecurityEventResponse struct {
	Recorded            bool   `protobuf:"varint,1,opt,name=recorded,proto3" json:"recorded,omitempty"`
	EventId             string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ThreatsBlockedTotal int32  `protobuf:"varint,3,opt,name=threats_blocked_total,json=threatsBlockedTotal,proto3" json:"threats_blocked_total,omitempty"`
}

func (m *SecurityEventResponse) Reset()         { *m = SecurityEventResponse{} }
func (m *SecurityEventResponse) String() string { b, _ := json.Marshal(m); return string(b) }
func (*SecurityEventResponse) ProtoMessage()    {}

func (m *SecurityEventResponse) Marshal() ([]byte, error) {
	var buf []byte
	if m.Recorded {
		buf = encodeVarintField(buf, 1, 1)
	}
	if len(m.EventId) > 0 {
		buf = encodeStringField(buf, 2, m.EventId)
	}
	if m.ThreatsBlockedTotal != 0 {
		buf = encodeVarintField(buf, 3, uint64(m.ThreatsBlockedTotal))
	}
	return buf, nil
}

func (m *SecurityEventResponse) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.Recorded = val != 0
			offset = next
		case 2:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.EventId = string(bytesVal)
			offset = next
		case 3:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.ThreatsBlockedTotal = int32(val)
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// VerifyRequest submits a Dilithium-5 signature or key for verification.
type VerifyRequest struct {
	KeyOrSignature     string `protobuf:"bytes,1,opt,name=key_or_signature,json=keyOrSignature,proto3" json:"key_or_signature,omitempty"`
	RawSignature       []byte `protobuf:"bytes,2,opt,name=raw_signature,json=rawSignature,proto3" json:"raw_signature,omitempty"`
	Message            []byte `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	PublicKey          []byte `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Context            string `protobuf:"bytes,5,opt,name=context,proto3" json:"context,omitempty"`
	EnforceActiveEpoch bool   `protobuf:"varint,6,opt,name=enforce_active_epoch,json=enforceActiveEpoch,proto3" json:"enforce_active_epoch,omitempty"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { b, _ := json.Marshal(m); return string(b) }
func (*VerifyRequest) ProtoMessage()    {}

func (m *VerifyRequest) Marshal() ([]byte, error) {
	var buf []byte
	if len(m.KeyOrSignature) > 0 {
		buf = encodeStringField(buf, 1, m.KeyOrSignature)
	}
	if len(m.RawSignature) > 0 {
		buf = encodeBytesField(buf, 2, m.RawSignature)
	}
	if len(m.Message) > 0 {
		buf = encodeBytesField(buf, 3, m.Message)
	}
	if len(m.PublicKey) > 0 {
		buf = encodeBytesField(buf, 4, m.PublicKey)
	}
	if len(m.Context) > 0 {
		buf = encodeStringField(buf, 5, m.Context)
	}
	if m.EnforceActiveEpoch {
		buf = encodeVarintField(buf, 6, 1)
	}
	return buf, nil
}

func (m *VerifyRequest) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.KeyOrSignature = string(bytesVal)
			offset = next
		case 2:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.RawSignature = append([]byte(nil), bytesVal...)
			offset = next
		case 3:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.Message = append([]byte(nil), bytesVal...)
			offset = next
		case 4:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.PublicKey = append([]byte(nil), bytesVal...)
			offset = next
		case 5:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.Context = string(bytesVal)
			offset = next
		case 6:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.EnforceActiveEpoch = val != 0
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// VerifyResponse returns the outcome of Dilithium-5 verification.
type VerifyResponse struct {
	Valid            bool    `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	VerificationType string  `protobuf:"bytes,2,opt,name=verification_type,json=verificationType,proto3" json:"verification_type,omitempty"`
	Epoch            float64 `protobuf:"fixed64,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	KeyHashSha256    string  `protobuf:"bytes,4,opt,name=key_hash_sha256,json=keyHashSha256,proto3" json:"key_hash_sha256,omitempty"`
	ErrorMessage     string  `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	VerifiedAtUnixMs int64   `protobuf:"varint,6,opt,name=verified_at_unix_ms,json=verifiedAtUnixMs,proto3" json:"verified_at_unix_ms,omitempty"`
	IsRevoked        bool    `protobuf:"varint,7,opt,name=is_revoked,json=isRevoked,proto3" json:"is_revoked,omitempty"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { b, _ := json.Marshal(m); return string(b) }
func (*VerifyResponse) ProtoMessage()    {}

func (m *VerifyResponse) Marshal() ([]byte, error) {
	var buf []byte
	if m.Valid {
		buf = encodeVarintField(buf, 1, 1)
	}
	if len(m.VerificationType) > 0 {
		buf = encodeStringField(buf, 2, m.VerificationType)
	}
	if m.Epoch != 0 {
		buf = encodeFixed64Field(buf, 3, math.Float64bits(m.Epoch))
	}
	if len(m.KeyHashSha256) > 0 {
		buf = encodeStringField(buf, 4, m.KeyHashSha256)
	}
	if len(m.ErrorMessage) > 0 {
		buf = encodeStringField(buf, 5, m.ErrorMessage)
	}
	if m.VerifiedAtUnixMs != 0 {
		buf = encodeVarintField(buf, 6, uint64(m.VerifiedAtUnixMs))
	}
	if m.IsRevoked {
		buf = encodeVarintField(buf, 7, 1)
	}
	return buf, nil
}

func (m *VerifyResponse) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.Valid = val != 0
			offset = next
		case 2:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.VerificationType = string(bytesVal)
			offset = next
		case 3:
			bits, next, err := readFixed64(data, offset)
			if err != nil {
				return err
			}
			m.Epoch = math.Float64frombits(bits)
			offset = next
		case 4:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.KeyHashSha256 = string(bytesVal)
			offset = next
		case 5:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.ErrorMessage = string(bytesVal)
			offset = next
		case 6:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.VerifiedAtUnixMs = int64(val)
			offset = next
		case 7:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.IsRevoked = val != 0
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// RegisterKeyRequest registers a newly generated Dilithium-5 key.
type RegisterKeyRequest struct {
	ActiveKey        string  `protobuf:"bytes,1,opt,name=active_key,json=activeKey,proto3" json:"active_key,omitempty"`
	RawKey           []byte  `protobuf:"bytes,2,opt,name=raw_key,json=rawKey,proto3" json:"raw_key,omitempty"`
	Epoch            float64 `protobuf:"fixed64,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Timestamp        int64   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OperatorIdentity string  `protobuf:"bytes,5,opt,name=operator_identity,json=operatorIdentity,proto3" json:"operator_identity,omitempty"`
}

func (m *RegisterKeyRequest) Reset()         { *m = RegisterKeyRequest{} }
func (m *RegisterKeyRequest) String() string { b, _ := json.Marshal(m); return string(b) }
func (*RegisterKeyRequest) ProtoMessage()    {}

func (m *RegisterKeyRequest) Marshal() ([]byte, error) {
	var buf []byte
	if len(m.ActiveKey) > 0 {
		buf = encodeStringField(buf, 1, m.ActiveKey)
	}
	if len(m.RawKey) > 0 {
		buf = encodeBytesField(buf, 2, m.RawKey)
	}
	if m.Epoch != 0 {
		buf = encodeFixed64Field(buf, 3, math.Float64bits(m.Epoch))
	}
	if m.Timestamp != 0 {
		buf = encodeVarintField(buf, 4, uint64(m.Timestamp))
	}
	if len(m.OperatorIdentity) > 0 {
		buf = encodeStringField(buf, 5, m.OperatorIdentity)
	}
	return buf, nil
}

func (m *RegisterKeyRequest) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.ActiveKey = string(bytesVal)
			offset = next
		case 2:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.RawKey = append([]byte(nil), bytesVal...)
			offset = next
		case 3:
			bits, next, err := readFixed64(data, offset)
			if err != nil {
				return err
			}
			m.Epoch = math.Float64frombits(bits)
			offset = next
		case 4:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.Timestamp = int64(val)
			offset = next
		case 5:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.OperatorIdentity = string(bytesVal)
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// RegisterKeyResponse returns the status of active key registration.
type RegisterKeyResponse struct {
	Ok                    bool    `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Epoch                 float64 `protobuf:"fixed64,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	KeyHashSha256         string  `protobuf:"bytes,3,opt,name=key_hash_sha256,json=keyHashSha256,proto3" json:"key_hash_sha256,omitempty"`
	RevokedPriorKeysCount int64   `protobuf:"varint,4,opt,name=revoked_prior_keys_count,json=revokedPriorKeysCount,proto3" json:"revoked_prior_keys_count,omitempty"`
	StatusMessage         string  `protobuf:"bytes,5,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
}

func (m *RegisterKeyResponse) Reset()         { *m = RegisterKeyResponse{} }
func (m *RegisterKeyResponse) String() string { b, _ := json.Marshal(m); return string(b) }
func (*RegisterKeyResponse) ProtoMessage()    {}

func (m *RegisterKeyResponse) Marshal() ([]byte, error) {
	var buf []byte
	if m.Ok {
		buf = encodeVarintField(buf, 1, 1)
	}
	if m.Epoch != 0 {
		buf = encodeFixed64Field(buf, 2, math.Float64bits(m.Epoch))
	}
	if len(m.KeyHashSha256) > 0 {
		buf = encodeStringField(buf, 3, m.KeyHashSha256)
	}
	if m.RevokedPriorKeysCount != 0 {
		buf = encodeVarintField(buf, 4, uint64(m.RevokedPriorKeysCount))
	}
	if len(m.StatusMessage) > 0 {
		buf = encodeStringField(buf, 5, m.StatusMessage)
	}
	return buf, nil
}

func (m *RegisterKeyResponse) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.Ok = val != 0
			offset = next
		case 2:
			bits, next, err := readFixed64(data, offset)
			if err != nil {
				return err
			}
			m.Epoch = math.Float64frombits(bits)
			offset = next
		case 3:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.KeyHashSha256 = string(bytesVal)
			offset = next
		case 4:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.RevokedPriorKeysCount = int64(val)
			offset = next
		case 5:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.StatusMessage = string(bytesVal)
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// KeyStatusRequest queries the current active key metadata.
type KeyStatusRequest struct {
	RequesterId string `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
}

func (m *KeyStatusRequest) Reset()         { *m = KeyStatusRequest{} }
func (m *KeyStatusRequest) String() string { b, _ := json.Marshal(m); return string(b) }
func (*KeyStatusRequest) ProtoMessage()    {}

func (m *KeyStatusRequest) Marshal() ([]byte, error) {
	var buf []byte
	if len(m.RequesterId) > 0 {
		buf = encodeStringField(buf, 1, m.RequesterId)
	}
	return buf, nil
}

func (m *KeyStatusRequest) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.RequesterId = string(bytesVal)
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// KeyStatusResponse contains active key metadata and revocation statistics.
type KeyStatusResponse struct {
	HasActiveKey      bool    `protobuf:"varint,1,opt,name=has_active_key,json=hasActiveKey,proto3" json:"has_active_key,omitempty"`
	ActiveKeyHash     string  `protobuf:"bytes,2,opt,name=active_key_hash,json=activeKeyHash,proto3" json:"active_key_hash,omitempty"`
	Epoch             float64 `protobuf:"fixed64,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	RegisteredAtUnix  int64   `protobuf:"varint,4,opt,name=registered_at_unix,json=registeredAtUnix,proto3" json:"registered_at_unix,omitempty"`
	RevokedPrevious   bool    `protobuf:"varint,5,opt,name=revoked_previous,json=revokedPrevious,proto3" json:"revoked_previous,omitempty"`
	Algorithm         string  `protobuf:"bytes,6,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	RevokedKeysCount  int64   `protobuf:"varint,7,opt,name=revoked_keys_count,json=revokedKeysCount,proto3" json:"revoked_keys_count,omitempty"`
}

func (m *KeyStatusResponse) Reset()         { *m = KeyStatusResponse{} }
func (m *KeyStatusResponse) String() string { b, _ := json.Marshal(m); return string(b) }
func (*KeyStatusResponse) ProtoMessage()    {}

func (m *KeyStatusResponse) Marshal() ([]byte, error) {
	var buf []byte
	if m.HasActiveKey {
		buf = encodeVarintField(buf, 1, 1)
	}
	if len(m.ActiveKeyHash) > 0 {
		buf = encodeStringField(buf, 2, m.ActiveKeyHash)
	}
	if m.Epoch != 0 {
		buf = encodeFixed64Field(buf, 3, math.Float64bits(m.Epoch))
	}
	if m.RegisteredAtUnix != 0 {
		buf = encodeVarintField(buf, 4, uint64(m.RegisteredAtUnix))
	}
	if m.RevokedPrevious {
		buf = encodeVarintField(buf, 5, 1)
	}
	if len(m.Algorithm) > 0 {
		buf = encodeStringField(buf, 6, m.Algorithm)
	}
	if m.RevokedKeysCount != 0 {
		buf = encodeVarintField(buf, 7, uint64(m.RevokedKeysCount))
	}
	return buf, nil
}

func (m *KeyStatusResponse) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.HasActiveKey = val != 0
			offset = next
		case 2:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.ActiveKeyHash = string(bytesVal)
			offset = next
		case 3:
			bits, next, err := readFixed64(data, offset)
			if err != nil {
				return err
			}
			m.Epoch = math.Float64frombits(bits)
			offset = next
		case 4:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.RegisteredAtUnix = int64(val)
			offset = next
		case 5:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.RevokedPrevious = val != 0
			offset = next
		case 6:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.Algorithm = string(bytesVal)
			offset = next
		case 7:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.RevokedKeysCount = int64(val)
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// SeedRequest requests a derived quantum-hardened seed.
type SeedRequest struct {
	Context            string `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	SeedBytes          int32  `protobuf:"varint,2,opt,name=seed_bytes,json=seedBytes,proto3" json:"seed_bytes,omitempty"`
	RequireTrueQuantum bool   `protobuf:"varint,3,opt,name=require_true_quantum,json=requireTrueQuantum,proto3" json:"require_true_quantum,omitempty"`
}

func (m *SeedRequest) Reset()         { *m = SeedRequest{} }
func (m *SeedRequest) String() string { b, _ := json.Marshal(m); return string(b) }
func (*SeedRequest) ProtoMessage()    {}

func (m *SeedRequest) Marshal() ([]byte, error) {
	var buf []byte
	if len(m.Context) > 0 {
		buf = encodeStringField(buf, 1, m.Context)
	}
	if m.SeedBytes != 0 {
		buf = encodeVarintField(buf, 2, uint64(m.SeedBytes))
	}
	if m.RequireTrueQuantum {
		buf = encodeVarintField(buf, 3, 1)
	}
	return buf, nil
}

func (m *SeedRequest) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.Context = string(bytesVal)
			offset = next
		case 2:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.SeedBytes = int32(val)
			offset = next
		case 3:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.RequireTrueQuantum = val != 0
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// SeedResponse returns the derived seed and entropy pool metrics.
type SeedResponse struct {
	Ok             bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	SeedHex        string   `protobuf:"bytes,2,opt,name=seed_hex,json=seedHex,proto3" json:"seed_hex,omitempty"`
	SeedBytes      []byte   `protobuf:"bytes,3,opt,name=seed_bytes,json=seedBytes,proto3" json:"seed_bytes,omitempty"`
	QuantumRatio   float64  `protobuf:"fixed64,4,opt,name=quantum_ratio,json=quantumRatio,proto3" json:"quantum_ratio,omitempty"`
	EntropySources []string `protobuf:"bytes,5,rep,name=entropy_sources,json=entropySources,proto3" json:"entropy_sources,omitempty"`
	HarvestedAtUnix int64   `protobuf:"varint,6,opt,name=harvested_at_unix,json=harvestedAtUnix,proto3" json:"harvested_at_unix,omitempty"`
}

func (m *SeedResponse) Reset()         { *m = SeedResponse{} }
func (m *SeedResponse) String() string { b, _ := json.Marshal(m); return string(b) }
func (*SeedResponse) ProtoMessage()    {}

func (m *SeedResponse) Marshal() ([]byte, error) {
	var buf []byte
	if m.Ok {
		buf = encodeVarintField(buf, 1, 1)
	}
	if len(m.SeedHex) > 0 {
		buf = encodeStringField(buf, 2, m.SeedHex)
	}
	if len(m.SeedBytes) > 0 {
		buf = encodeBytesField(buf, 3, m.SeedBytes)
	}
	if m.QuantumRatio != 0 {
		buf = encodeFixed64Field(buf, 4, math.Float64bits(m.QuantumRatio))
	}
	for _, s := range m.EntropySources {
		buf = encodeStringField(buf, 5, s)
	}
	if m.HarvestedAtUnix != 0 {
		buf = encodeVarintField(buf, 6, uint64(m.HarvestedAtUnix))
	}
	return buf, nil
}

func (m *SeedResponse) Unmarshal(data []byte) error {
	offset := 0
	for offset < len(data) {
		tag, next, err := readVarint(data, offset)
		if err != nil {
			return err
		}
		offset = next
		wireType := int(tag & 0x07)
		fieldNum := int(tag >> 3)

		switch fieldNum {
		case 1:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.Ok = val != 0
			offset = next
		case 2:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.SeedHex = string(bytesVal)
			offset = next
		case 3:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.SeedBytes = append([]byte(nil), bytesVal...)
			offset = next
		case 4:
			bits, next, err := readFixed64(data, offset)
			if err != nil {
				return err
			}
			m.QuantumRatio = math.Float64frombits(bits)
			offset = next
		case 5:
			bytesVal, next, err := readLengthDelimited(data, offset)
			if err != nil {
				return err
			}
			m.EntropySources = append(m.EntropySources, string(bytesVal))
			offset = next
		case 6:
			val, next, err := readVarint(data, offset)
			if err != nil {
				return err
			}
			m.HarvestedAtUnix = int64(val)
			offset = next
		default:
			offset, err = skipField(data, offset, wireType)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

// skipField skips unmapped wire fields to ensure forward compatibility.
func skipField(data []byte, offset int, wireType int) (int, error) {
	switch wireType {
	case 0: // varint
		_, next, err := readVarint(data, offset)
		return next, err
	case 1: // fixed64
		if offset+8 > len(data) {
			return offset, fmt.Errorf("unexpected EOF skipping fixed64")
		}
		return offset + 8, nil
	case 2: // length-delimited
		_, next, err := readLengthDelimited(data, offset)
		return next, err
	case 5: // fixed32
		if offset+4 > len(data) {
			return offset, fmt.Errorf("unexpected EOF skipping fixed32")
		}
		return offset + 4, nil
	default:
		return offset, fmt.Errorf("unsupported wire type %d", wireType)
	}
}
