begin;

create table if not exists public.hashcod_platform_registrations (
  id bigint generated by default as identity primary key,
  full_name_enc text not null check (full_name_enc like 'l8e1:%'),
  age smallint not null check (age between 18 and 120),
  cedula_enc text not null check (cedula_enc like 'l8e1:%'),
  platform_name text not null check (char_length(platform_name) between 2 and 120),
  email_enc text not null check (email_enc like 'l8e1:%'),
  phone_enc text not null check (phone_enc like 'l8e1:%'),
  created_at timestamptz not null default now()
);

alter table public.hashcod_platform_registrations enable row level security;

revoke all on table public.hashcod_platform_registrations from public, anon, authenticated;
grant select, insert on table public.hashcod_platform_registrations to service_role;

drop policy if exists hashcod_platform_registrations_deny_direct
  on public.hashcod_platform_registrations;
create policy hashcod_platform_registrations_deny_direct
  on public.hashcod_platform_registrations
  for all
  to public
  using (false)
  with check (false);

revoke all on sequence public.hashcod_platform_registrations_id_seq from public, anon, authenticated;
grant usage, select on sequence public.hashcod_platform_registrations_id_seq to service_role;

create index if not exists hashcod_platform_registrations_created_at_idx
  on public.hashcod_platform_registrations (created_at desc);

comment on table public.hashcod_platform_registrations is
  'Adult platform-registration intake submitted through Hashcod Codespace. Personal identity/contact fields are AES-256-GCM envelopes; direct anon/authenticated access is denied; backend service role only.';

commit;
