-- Hashcod Codespace global collaborative persistence
-- Applied to Supabase on 2026-09-13.
-- Server-side access only: browser clients reach these tables through
-- hashcod-sync.php, never with a service-role credential.

begin;

create table if not exists public.hashcod_shared_links (
  slot smallint primary key check (slot between 0 and 199),
  url text not null check (char_length(url) between 1 and 4096),
  code_hash text not null check (code_hash ~ '^[0-9a-f]{64}$'),
  created_at_ms bigint not null check (created_at_ms > 0),
  updated_at_ms bigint not null check (updated_at_ms >= created_at_ms),
  updated_by text not null default 'platform',
  updated_at timestamptz not null default now()
);

create index if not exists hashcod_shared_links_updated_idx
  on public.hashcod_shared_links (updated_at_ms desc);

create table if not exists public.hashcod_shared_images (
  id text primary key check (char_length(id) between 1 and 96),
  filename text not null check (char_length(filename) between 1 and 255),
  mime_type text not null default 'image/png' check (mime_type = 'image/png'),
  size_bytes bigint not null check (size_bytes between 1 and 15728640),
  sha256 text not null check (sha256 ~ '^[0-9a-f]{64}$'),
  storage_path text not null unique,
  code_hash text not null check (code_hash ~ '^[0-9a-f]{64}$'),
  created_at_ms bigint not null check (created_at_ms > 0),
  updated_at_ms bigint not null check (updated_at_ms >= created_at_ms),
  is_deleted boolean not null default false,
  updated_by text not null default 'platform',
  updated_at timestamptz not null default now()
);

create index if not exists hashcod_shared_images_live_idx
  on public.hashcod_shared_images (is_deleted, updated_at_ms desc);

create table if not exists public.hashcod_sync_events (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('link','image','system')),
  entity_key text not null,
  action text not null check (action in ('upsert','delete','sync')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists hashcod_sync_events_created_idx
  on public.hashcod_sync_events (created_at desc);

alter table public.hashcod_shared_links enable row level security;
alter table public.hashcod_shared_images enable row level security;
alter table public.hashcod_sync_events enable row level security;

drop policy if exists hashcod_shared_links_server_only on public.hashcod_shared_links;
create policy hashcod_shared_links_server_only on public.hashcod_shared_links
  for all to public using (false) with check (false);

drop policy if exists hashcod_shared_images_server_only on public.hashcod_shared_images;
create policy hashcod_shared_images_server_only on public.hashcod_shared_images
  for all to public using (false) with check (false);

drop policy if exists hashcod_sync_events_server_only on public.hashcod_sync_events;
create policy hashcod_sync_events_server_only on public.hashcod_sync_events
  for all to public using (false) with check (false);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('l8-storage', 'l8-storage', false, 15728640, array['image/png']::text[])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'hashcod_shared_links'
  ) then
    alter publication supabase_realtime add table public.hashcod_shared_links;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'hashcod_shared_images'
  ) then
    alter publication supabase_realtime add table public.hashcod_shared_images;
  end if;
end $$;

commit;

create or replace function public.hashcod_sync_upsert_links(
  p_links jsonb,
  p_actor text default 'platform'
)
returns setof public.hashcod_shared_links
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.hashcod_shared_links (
    slot, url, code_hash, created_at_ms, updated_at_ms, updated_by, updated_at
  )
  select
    (item->>'slot')::smallint,
    item->>'url',
    lower(item->>'codeHash'),
    (item->>'createdAt')::bigint,
    (item->>'updatedAt')::bigint,
    left(coalesce(nullif(p_actor,''),'platform'), 160),
    now()
  from jsonb_array_elements(coalesce(p_links, '[]'::jsonb)) as item
  where (item->>'slot') ~ '^[0-9]+$'
    and (item->>'slot')::int between 0 and 199
    and char_length(coalesce(item->>'url','')) between 1 and 4096
    and lower(coalesce(item->>'codeHash','')) ~ '^[0-9a-f]{64}$'
    and coalesce(item->>'createdAt','') ~ '^[0-9]+$'
    and coalesce(item->>'updatedAt','') ~ '^[0-9]+$'
  on conflict (slot) do update set
    url = excluded.url,
    code_hash = excluded.code_hash,
    created_at_ms = least(public.hashcod_shared_links.created_at_ms, excluded.created_at_ms),
    updated_at_ms = excluded.updated_at_ms,
    updated_by = excluded.updated_by,
    updated_at = now()
  where excluded.updated_at_ms >= public.hashcod_shared_links.updated_at_ms;

  return query
  select * from public.hashcod_shared_links order by slot;
end;
$$;

revoke all on function public.hashcod_sync_upsert_links(jsonb, text)
  from public, anon, authenticated;
grant execute on function public.hashcod_sync_upsert_links(jsonb, text)
  to service_role;
