begin;

create table if not exists public.hashcod_platform_registrations (
  id bigint generated by default as identity primary key,
  full_name text not null check (char_length(full_name) between 4 and 120),
  age smallint not null check (age between 18 and 120),
  cedula text not null check (cedula ~ '^[0-9]{3}-[0-9]{7}-[0-9]$'),
  platform_name text not null check (char_length(platform_name) between 2 and 120),
  email text not null check (char_length(email) between 3 and 254),
  phone text not null check (char_length(phone) between 7 and 32),
  created_at timestamptz not null default now()
);

alter table public.hashcod_platform_registrations enable row level security;

revoke all on table public.hashcod_platform_registrations from anon, authenticated;
grant select, insert on table public.hashcod_platform_registrations to service_role;

revoke all on sequence public.hashcod_platform_registrations_id_seq from anon, authenticated;
grant usage, select on sequence public.hashcod_platform_registrations_id_seq to service_role;

create index if not exists hashcod_platform_registrations_created_at_idx
  on public.hashcod_platform_registrations (created_at desc);

comment on table public.hashcod_platform_registrations is
  'Adult platform-registration intake submitted through Hashcod Codespace. Direct anon/authenticated access is denied; backend service role only.';

commit;
