// Catalog of the bundled PSOT form PDFs (assets/forms/<code>_*.pdf, served by forms-library.php).
// Rows: [code, title]. Keep in sync with the files; tests/test_forms_library.php checks it.
export const FORM_CATEGORIES = [
  { id: "U", title: "Cuenta de usuario", forms: [
    ["U01", "Registro de usuario"],
    ["U02", "Verificación de correo"],
  ] },
  { id: "A", title: "A · Identidad y llaves", forms: [
    ["A00", "Verificación de teléfono"],
    ["A01", "Verificación de identidad (KYC)"],
    ["A02", "Registro de persona jurídica"],
    ["A03", "Designación de representante legal"],
    ["A04", "Creación de identidad digital (DID)"],
    ["A05", "Registro de llave pública"],
    ["A06", "Rotación de llaves"],
    ["A07", "Reporte de llave comprometida"],
    ["A08", "Configuración de 2FA"],
    ["A09", "Perfil profesional del creador"],
  ] },
  { id: "B", title: "B · Consentimientos y políticas", forms: [
    ["B13", "Aceptación de términos de servicio"],
    ["B14", "Aceptación de política de privacidad"],
    ["B15", "Aviso de alcance de la constancia"],
    ["B16", "Consentimiento de firma electrónica"],
    ["B17", "Consentimiento de verificación de identidad"],
    ["B18", "Consentimiento de publicación"],
    ["B19", "Consentimiento de anclaje externo"],
    ["B20", "Consentimiento de comunicaciones"],
    ["B21", "Política de retención de datos"],
    ["B22", "Aceptación de tarifas"],
    ["B23", "Política de uso aceptable"],
    ["B24", "Re-aceptación por cambio de términos"],
  ] },
  { id: "C", title: "C · Autoría y declaraciones", forms: [
    ["C25", "Declaración jurada de autoría"],
    ["C26", "Declaración de coautoría"],
    ["C27", "Aceptación de coautor"],
    ["C28", "Declaración de obra por encargo"],
    ["C29", "Declaración de titularidad empresarial"],
    ["C30", "Declaración de uso de IA en la creación"],
    ["C31", "Declaración de aporte humano"],
    ["C32", "Declaración de obra derivada"],
    ["C33", "Declaración de componentes de terceros"],
    ["C34", "Declaración de licencias open source"],
    ["C35", "Declaración de originalidad"],
    ["C36", "Vinculación con registros oficiales"],
  ] },
  { id: "D", title: "D · Modelos, datasets y prompts", forms: [
    ["D37", "Registro de modelo de IA"],
    ["D38", "Registro de pesos del modelo"],
    ["D39", "Registro de versión de modelo"],
    ["D40", "Registro de fine-tuning"],
    ["D41", "Registro de dataset"],
    ["D42", "Manifiesto de archivos del dataset"],
    ["D43", "Declaración de origen de datos"],
    ["D44", "Declaración de datos personales en el dataset"],
    ["D45", "Registro de configuración de entrenamiento"],
    ["D46", "Registro de resultados de evaluación"],
    ["D47", "Registro de prompt"],
    ["D48", "Registro de paquete de prompts"],
    ["D49", "Registro de agente de IA"],
    ["D50", "Registro de skill"],
    ["D51", "Registro de código fuente"],
    ["D52", "Registro de API o servicio de IA"],
    ["D53", "Registro de output generado"],
    ["D54", "Ficha técnica del modelo (model card)"],
  ] },
  { id: "E", title: "E · Bitácora y trazabilidad", forms: [
    ["E55", "Bitácora de desarrollo"],
    ["E56", "Registro de hito"],
    ["E57", "Registro de idea o concepto inicial"],
    ["E58", "Registro de borrador o prototipo"],
    ["E59", "Registro de reunión o colaboración"],
    ["E60", "Registro de entorno de ejecución"],
    ["E61", "Snapshot periódico automático"],
    ["E62", "Registro de entrega a terceros"],
    ["E63", "Registro de recepción"],
    ["E64", "Registro de acceso al activo"],
    ["E65", "Registro de demostración pública"],
    ["E66", "Registro de acuerdo de confidencialidad (NDA)"],
  ] },
  { id: "F", title: "F · Licencias y cesiones", forms: [
    ["F67", "Emisión de licencia de uso"],
    ["F68", "Aceptación de licencia por el licenciatario"],
    ["F69", "Licencia exclusiva"],
    ["F70", "Licencia comercial de prompts o skills"],
    ["F71", "Cesión de derechos"],
    ["F72", "Aceptación de cesión"],
    ["F73", "Transferencia de persona física a empresa"],
    ["F74", "Registro de regalías"],
    ["F75", "Registro de pago recibido"],
    ["F76", "Renovación de licencia"],
    ["F77", "Terminación de licencia"],
    ["F78", "Sublicencia"],
  ] },
  { id: "G", title: "G · Verificación y disputas", forms: [
    ["G79", "Solicitud de verificación pública"],
    ["G80", "Solicitud de reporte de verificación"],
    ["G81", "Solicitud de expediente probatorio"],
    ["G82", "Revocación de registro"],
    ["G83", "Corrección de datos de un registro"],
    ["G84", "Reclamo de titularidad por tercero"],
    ["G85", "Respuesta al reclamo"],
    ["G86", "Reporte de infracción"],
    ["G87", "Solicitud de retiro de contenido"],
    ["G88", "Contra-notificación"],
    ["G89", "Solicitud de autoridad judicial o administrativa"],
    ["G90", "Registro de resolución de disputa"],
  ] },
  { id: "H", title: "H · Privacidad, seguridad y auditoría", forms: [
    ["H91", "Ejercicio de derechos ARCO"],
    ["H92", "Solicitud de exportación de datos"],
    ["H93", "Solicitud de cierre de cuenta"],
    ["H94", "Reporte de incidente de seguridad"],
    ["H95", "Bitácora de ceremonia de llaves de Hashcod"],
    ["H96", "Bitácora de operación de la TSA"],
    ["H97", "Registro de auditoría interna"],
    ["H98", "Registro de cambios del sistema"],
    ["H99", "Declaración de prácticas de registro"],
    ["H100", "Encuesta de satisfacción y uso"],
  ] },
];
