import React, { useEffect, useLayoutEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { ReviewIcon } from './ReviewIcons';
import './review-chat.css';

const STATES={pending:'Pendiente',in_progress:'En curso',delayed:'Retrasada',awaiting_payment:'Falta de pago',completed:'Completada',under_review:'En revisión',certified:'Certificada',rejected:'Rechazada'};
const CHECKS={sandbox:'Aislamiento',tests:'Pruebas',sast:'Código',secrets:'Secretos',deps:'Dependencias'};
function WhatsAppIcon(){return <svg viewBox="0 0 48 48" aria-hidden="true"><path fill="#fff" d="M4.868,43.303l2.694-9.835C5.9,30.59,5.026,27.324,5.027,23.979C5.032,13.514,13.548,5,24.014,5c5.079,0.002,9.845,1.979,13.43,5.566c3.584,3.588,5.558,8.356,5.556,13.428c-0.004,10.465-8.522,18.98-18.986,18.98h-0.008c-3.177-0.001-6.3-0.798-9.073-2.311L4.868,43.303z"/><path fill="#cfd8dc" d="M24.014,4C12.998,4,4.032,12.962,4.027,23.979c-0.001,3.367,0.849,6.685,2.461,9.622l-2.585,9.439c-0.094,0.345,0.002,0.713,0.254,0.967c0.19,0.192,0.447,0.297,0.711,0.297c0.085,0,0.17-0.011,0.254-0.033l9.687-2.54c2.828,1.468,5.998,2.243,9.197,2.244c11.024,0,19.99-8.963,19.995-19.98c0.002-5.339-2.075-10.359-5.848-14.135C34.378,6.083,29.357,4.002,24.014,4z"/><path fill="#40c351" d="M35.176,12.832c-2.98-2.982-6.941-4.625-11.157-4.626c-8.704,0-15.783,7.076-15.787,15.774c-0.001,2.981,0.833,5.883,2.413,8.396l0.376,0.597l-1.595,5.821l5.973-1.566l0.577,0.342c2.422,1.438,5.2,2.198,8.032,2.199h0.006c8.698,0,15.777-7.077,15.78-15.776C39.795,19.778,38.156,15.814,35.176,12.832z"/><path fill="#fff" fillRule="evenodd" d="M19.268,16.045c-0.355-0.79-0.729-0.806-1.068-0.82c-0.277-0.012-0.593-0.011-0.909-0.011c-0.316,0-0.83,0.119-1.265,0.594c-0.435,0.475-1.661,1.622-1.661,3.956c0,2.334,1.7,4.59,1.937,4.906c0.237,0.316,3.282,5.259,8.104,7.161c4.007,1.58,4.823,1.266,5.693,1.187c0.87-0.079,2.807-1.147,3.202-2.255c0.395-1.108,0.395-2.057,0.277-2.255c-0.119-0.198-0.435-0.316-0.909-0.554s-2.807-1.385-3.242-1.543c-0.435-0.158-0.751-0.237-1.068,0.238c-0.316,0.474-1.225,1.543-1.502,1.859c-0.277,0.317-0.554,0.357-1.028,0.119c-0.474-0.238-2.002-0.738-3.815-2.354c-1.41-1.257-2.362-2.81-2.639-3.285c-0.277-0.474-0.03-0.731,0.208-0.968c0.213-0.213,0.474-0.554,0.712-0.831c0.237-0.277,0.316-0.475,0.474-0.791c0.158-0.317,0.079-0.594-0.04-0.831C20.612,19.329,19.69,16.983,19.268,16.045z" clipRule="evenodd"/></svg>;}

export default function ReviewChat({onClose}) {
  const [rows,setRows]=useState([]),[config,setConfig]=useState(null),[selected,setSelected]=useState('');
  const [apiKey,setApiKey]=useState(''),[model,setModel]=useState('claude-sonnet-5-5'),[budget,setBudget]=useState('1'),[consent,setConsent]=useState(false);
  const [session,setSession]=useState(''),[messages,setMessages]=useState([]),[checks,setChecks]=useState([]),[draft,setDraft]=useState('');
  const [tab,setTab]=useState('Chat'),[busy,setBusy]=useState(true),[error,setError]=useState(''),[result,setResult]=useState(''),[certificate,setCertificate]=useState(null),[reserved,setReserved]=useState(0);
  const root=useRef(null),thread=useRef(null),csrf=useRef(''),pending=useRef(false),alive=useRef(true),abort=useRef(null);
  useLayoutEffect(()=>{
    const previous=document.activeElement,targets=[...document.querySelectorAll('body > main,body > footer')],states=targets.map(n=>n.inert),overflow=document.body.style.overflow;
    targets.forEach(n=>{n.inert=true;});document.body.style.overflow='hidden';root.current?.querySelector('button')?.focus();
    return ()=>{targets.forEach((n,i)=>{n.inert=document.body.classList.contains('hpa-locked')?true:states[i];});document.body.style.overflow=overflow;previous?.focus?.();};
  },[]);
  useEffect(()=>{refresh().catch(e=>alive.current&&setError(e.message)).finally(()=>alive.current&&setBusy(false));return()=>{alive.current=false;abort.current?.abort();};},[]);
  useEffect(()=>{thread.current?.scrollTo({top:thread.current.scrollHeight,behavior:'auto'});},[messages,busy]);
  async function request(body,url='/api/hashcod-review') {
    const controller=new AbortController();abort.current=controller;const timer=setTimeout(()=>controller.abort(),150000);
    try{
      const response=await fetch(url,{method:body?'POST':'GET',credentials:'same-origin',cache:'no-store',signal:controller.signal,
        headers:body?{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest','X-Hashcod-Review-CSRF':csrf.current}:{},body:body?JSON.stringify(body):undefined});
      const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'No se pudo completar la revisión.');return data;
    }finally{clearTimeout(timer);}
  }
  async function refresh(){const data=await request();if(!alive.current)return;csrf.current=data.csrf;setRows(data.requests);setConfig(data.config);setSelected(current=>data.requests.some(r=>r.id===current)?current:(data.requests[0]?.id||''));}
  async function run(work){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await work();}catch(e){if(alive.current)setError(e.name==='AbortError'?'La conexión tardó demasiado. Actualiza para consultar el resultado.':e.message);}finally{pending.current=false;if(alive.current)setBusy(false);}}
  async function verifyCertificate(c){if(!c)return;const id=c.payload?.certificate_id||c.id;const verified=await request(null,'/api/hashcod-review/verify?id='+encodeURIComponent(id));if(alive.current)setCertificate(verified.valid?{...c,id}:null);if(!verified.valid&&alive.current)setError('El certificado fue revocado o el archivo ya no coincide.');}
  async function start(){const key=apiKey;setApiKey('');await run(async()=>{const data=await request({action:'start',id:selected,api_key:key,model,consent,budget_micros:Math.round(Number(budget)*1000000)});if(!alive.current)return;setSession(data.session_id);setMessages([{role:'assistant',body:data.reply}]);setChecks(data.checks);setResult('');setCertificate(null);setReserved(0);setTab('Chat');await refresh();});}
  async function send(){const text=draft.trim();if(!text||!session)return;setDraft('');await run(async()=>{const data=await request({action:'message',session_id:session,text});if(alive.current){setMessages(current=>[...current,{role:'user',body:text},{role:'assistant',body:data.reply}]);setReserved(current=>current+(data.reservedUsd||0));}});}
  async function finalize(){await run(async()=>{const data=await request({action:'finalize',session_id:session});if(!alive.current)return;setResult(data.result);setReserved(current=>current+(data.reservedUsd||0));setTab('Resultado');if(data.summary)setMessages(current=>[...current,{role:'assistant',body:data.summary}]);await verifyCertificate(data.certificate);await refresh();});}
  async function history(){const row=rows.find(r=>r.id===selected);if(!row?.sessionId)return;await run(async()=>{const data=await request({action:'history',session_id:row.sessionId});if(!alive.current)return;setSession(row.sessionId);setModel(data.session.model);setMessages(data.messages);setChecks(data.checks);setReserved(Number(data.session.reserved_micros)/1000000);setResult(data.session.status==='active'?'':data.session.status);setTab('Chat');await verifyCertificate(data.certificate);});}
  async function close(){if(busy)return;if(session&&!result){await run(async()=>{await request({action:'close',session_id:session});onClose();});}else onClose();}
  async function reset(){await run(async()=>{if(session&&!result)await request({action:'close',session_id:session});if(!alive.current)return;setSession('');setMessages([]);setChecks([]);setResult('');setCertificate(null);setApiKey('');setConsent(false);setTab('Chat');await refresh();});}
  const row=rows.find(r=>r.id===selected),price=config?.models.find(m=>m.id===model);
  const estimate=price?((Number(row?.size||0)*6+12000)*price.inputUsdPerMillion+2000*price.outputUsdPerMillion)/1000000:0;
  const validBudget=Number(budget)>=.1&&Number(budget)<=20;
  return createPortal(<div className="hrc-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget&&!busy)close();}}><section ref={root} id="d5ReviewChat" className="hrc-shell" role="dialog" aria-modal="true" aria-labelledby="hrc-title" onKeyDown={e=>{
    if(e.key==='Escape'&&!busy){e.preventDefault();close();}if(e.key!=='Tab')return;
    const nodes=[...root.current.querySelectorAll('button,input,select,a[href]')].filter(n=>!n.disabled&&n.offsetParent!==null);if(e.shiftKey&&document.activeElement===nodes[0]){e.preventDefault();nodes.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===nodes.at(-1)){e.preventDefault();nodes[0]?.focus();}
  }}><header className="hrc-heading"><div className="hrc-brand"><ReviewIcon/><div><span>Hashcod Codespace</span><h2 id="hrc-title">Revisión de solicitudes</h2></div></div><button className="hrc-icon-button" aria-label="Cerrar revisión" disabled={busy} onClick={close}>×</button></header>
    <div className="hrc-context"><label htmlFor="hrc-request">Tu solicitud</label><select id="hrc-request" disabled={busy||!!session} value={selected} onChange={e=>{setSelected(e.target.value);setCertificate(null);}}><option value="">Selecciona una solicitud</option>{rows.map(r=><option key={r.id} value={r.id}>{r.name} · {STATES[r.status]||r.status}</option>)}</select>
      {!rows.length&&!busy&&<p>Envía primero un archivo desde Tokenización. Aquí aparecerán las solicitudes de tu sesión de acceso.</p>}
      {!session&&row?.sessionId&&<button type="button" className="hrc-text-button" disabled={busy} onClick={history}>Consultar revisión guardada</button>}
    </div>
    {!session&&config&&<form className="hrc-setup" onSubmit={e=>{e.preventDefault();start();}}><div className="hrc-fields"><label>Modelo<select value={model} disabled={busy} onChange={e=>setModel(e.target.value)}>{config.models.map(m=><option key={m.id} value={m.id}>{m.id.replace('claude-','Claude ')}</option>)}</select></label><label>Presupuesto máximo USD<input type="number" min="0.10" max="20" step="0.10" value={budget} disabled={busy} onChange={e=>setBudget(e.target.value)}/></label></div>
      <label>API key de Anthropic<input type="password" autoComplete="off" spellCheck={false} maxLength={320} value={apiKey} disabled={busy} onChange={e=>setApiKey(e.target.value)} placeholder="sk-ant-…" required/></label>
      <p>Validar la clave no genera una respuesta de IA. Primera respuesta: máximo estimado US${estimate.toFixed(3)}. Cada conversación consume tu cuota del proveedor hasta el presupuesto indicado.</p>
      <label className="hrc-consent"><input type="checkbox" checked={consent} disabled={busy} onChange={e=>setConsent(e.target.checked)} required/><span>Autorizo enviar este archivo y mis mensajes a Anthropic para revisarlos. La clave se cifra temporalmente por 30 minutos y se elimina al terminar. <a href="/privacy#dpa-ia" target="_blank" rel="noopener noreferrer">Política de uso y privacidad</a>.</span></label>
      <button className="hrc-primary" disabled={busy||!row?.available||!apiKey.trim()||!consent||!validBudget}>{busy?'Comprobando archivo…':'Validar clave y comenzar'}</button><p className="hrc-footnote">Python y JavaScript · Hasta 128 KB · {config.scope}</p>
    </form>}
    {session&&<><div className="hrc-review-card"><div className="hrc-tabs"><div>{['Chat','Comprobaciones','Resultado'].map(name=><button key={name} aria-pressed={tab===name} onClick={()=>setTab(name)}>{name}</button>)}</div><button className="hrc-icon-button" aria-label="Nueva revisión" disabled={busy} onClick={reset}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 5v14M5 12h14"/></svg></button></div>
      <div ref={thread} className="hrc-thread" aria-live="polite" aria-busy={busy}>{tab==='Chat'?messages.map((m,i)=><div key={i} className={m.role==='user'?'hrc-user':'hrc-reply'}>{m.role==='assistant'&&<div className="hrc-reply-label"><strong>Revisión</strong><span>Hashcod · {model}</span></div>}<p>{m.body}</p></div>):tab==='Comprobaciones'?checks.map(c=><div key={c.kind} className="hrc-check"><strong>{CHECKS[c.kind]}</strong><span className={c.status==='complete'&&c.passed?'hrc-good':'hrc-pending'}>{c.status!=='complete'?'Revisión humana':c.passed?'Comprobado':'Hallazgos'}</span><p>{c.tool} {c.tool_version} · {c.scope}</p></div>):<div className="hrc-result"><strong>{certificate?'Solicitud verificada':result==='fail'?'Revisión rechazada':result==='needs_human'?'Se requiere revisión humana':result?'Sesión terminada':'Dictamen pendiente'}</strong><p>{certificate?'El certificado identifica esta versión del archivo y el alcance de las comprobaciones.':'Solicita el dictamen final después de revisar los resultados. No se emite certificado con comprobaciones incompletas.'}</p>{certificate&&<a href={'/api/hashcod-review/verify?id='+encodeURIComponent(certificate.id)} target="_blank" rel="noopener noreferrer">Consultar certificado firmado</a>}</div>}</div>
      <form className="hrc-composer" onSubmit={e=>{e.preventDefault();send();}}><div><input aria-label="Mensaje para el revisor" placeholder="Pregunta sobre tu archivo…" maxLength={4000} value={draft} onChange={e=>setDraft(e.target.value)} disabled={busy||!!result}/><button aria-label="Enviar mensaje" disabled={busy||!!result||!draft.trim()}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.4"><path d="M12 19V5M5 12l7-7 7 7"/></svg></button></div></form></div>
      <div className="hrc-final-actions"><span>Uso máximo: US${reserved.toFixed(3)}</span><button className="hrc-primary" disabled={busy||!!result} onClick={finalize}>{busy?'Revisando…':'Solicitar dictamen final'}</button></div>
      {certificate&&<a className="hrc-whatsapp" href={'https://wa.me/18294721257?text='+encodeURIComponent(`Hola DIKTATCART. Mi solicitud ${selected} fue verificada. Certificado: https://hashcodcodespace.dev/api/hashcod-review/verify?id=${certificate.id}`)} target="_blank" rel="noopener noreferrer"><WhatsAppIcon/><span>Continuar con DIKTATCART</span></a>}
    </>}
    {error&&<p className="hrc-error" role="alert">{error}</p>}{busy&&<p className="hrc-progress" role="status">Procesando de forma segura…</p>}
  </section></div>,document.body);
}
